# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Browser Domain Commands"""

from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..target.types import TargetID
    from .types import Bounds
    from .types import WindowID


class GetWindowForTargetParameters(TypedDict):
    targetId: "TargetID"
    """Devtools agent host id."""


class GetWindowForTargetReturns(TypedDict):
    windowId: "WindowID"
    """Browser window id."""
    bounds: "Bounds"
    """Bounds information of the window. When window state is 'minimized', the restored window position and size are returned."""


class GetVersionReturns(TypedDict):
    protocolVersion: "str"
    """Protocol version."""
    product: "str"
    """Product name."""
    revision: "str"
    """Product revision."""
    userAgent: "str"
    """User-Agent."""
    jsVersion: "str"
    """V8 version."""


class SetWindowBoundsParameters(TypedDict):
    windowId: "WindowID"
    """Browser window id."""
    bounds: "Bounds"
    """New window bounds. The 'minimized', 'maximized' and 'fullscreen' states cannot be combined with 'left', 'top', 'width' or 'height'. Leaves unspecified fields unchanged."""


class GetWindowBoundsParameters(TypedDict):
    windowId: "WindowID"
    """Browser window id."""


class GetWindowBoundsReturns(TypedDict):
    bounds: "Bounds"
    """Bounds information of the window. When window state is 'minimized', the restored window position and size are returned."""
