# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Browser Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import GetVersionReturns
    from .commands import GetWindowBoundsParameters
    from .commands import GetWindowBoundsReturns
    from .commands import GetWindowForTargetParameters
    from .commands import GetWindowForTargetReturns
    from .commands import SetWindowBoundsParameters


class BrowserClient:
    """Client for Browser domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def close(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Close browser gracefully."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Browser.close",
                params=params,
                session_id=session_id,
            ),
        )

    async def getWindowForTarget(
        self,
        params: "GetWindowForTargetParameters",
        session_id: Optional[str] = None,
    ) -> "GetWindowForTargetReturns":
        """Get the browser window that contains the devtools target."""
        return cast(
            "GetWindowForTargetReturns",
            await self._client.send_raw(
                method="Browser.getWindowForTarget",
                params=params,
                session_id=session_id,
            ),
        )

    async def getVersion(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetVersionReturns":
        """Returns version information."""
        return cast(
            "GetVersionReturns",
            await self._client.send_raw(
                method="Browser.getVersion",
                params=params,
                session_id=session_id,
            ),
        )

    async def setWindowBounds(
        self,
        params: "SetWindowBoundsParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Set position and/or size of the browser window."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Browser.setWindowBounds",
                params=params,
                session_id=session_id,
            ),
        )

    async def getWindowBounds(
        self,
        params: "GetWindowBoundsParameters",
        session_id: Optional[str] = None,
    ) -> "GetWindowBoundsReturns":
        """Get position and size of the browser window."""
        return cast(
            "GetWindowBoundsReturns",
            await self._client.send_raw(
                method="Browser.getWindowBounds",
                params=params,
                session_id=session_id,
            ),
        )
