# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Browser Domain Types"""

from typing_extensions import Literal
from typing_extensions import TypedDict

WindowID = int


WindowState = Literal["normal", "minimized", "maximized", "fullscreen"]
"""The state of the browser window."""


class Bounds(TypedDict, total=False):
    """Browser window bounds information"""

    left: "int"
    """The offset from the left edge of the screen to the window in pixels."""
    top: "int"
    """The offset from the top edge of the screen to the window in pixels."""
    width: "int"
    """The window width in pixels."""
    height: "int"
    """The window height in pixels."""
    windowState: "WindowState"
    """The window state. Default to normal."""
