# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Audits Domain Library"""

from typing import Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import GetEncodedResponseParameters
    from .commands import GetEncodedResponseReturns


class AuditsClient:
    """Client for Audits domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def getEncodedResponse(
        self,
        params: "GetEncodedResponseParameters",
        session_id: Optional[str] = None,
    ) -> "GetEncodedResponseReturns":
        """Returns the response body and size if it were re-encoded with the specified settings. Only applies to images."""
        return cast(
            "GetEncodedResponseReturns",
            await self._client.send_raw(
                method="Audits.getEncodedResponse",
                params=params,
                session_id=session_id,
            ),
        )
