# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Page Domain Commands"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..debugger.types import SearchMatch
    from ..dom.types import Rect
    from ..emulation.types import ScreenOrientation
    from ..network.types import Cookie
    from ..network.types import LoaderId
    from ..runtime.types import ExecutionContextId
    from .types import AppManifestError
    from .types import FrameId
    from .types import FrameResourceTree
    from .types import FrameTree
    from .types import LayoutViewport
    from .types import NavigationEntry
    from .types import ScriptIdentifier
    from .types import TransitionType
    from .types import Viewport
    from .types import VisualViewport


class AddScriptToEvaluateOnLoadParameters(TypedDict):
    scriptSource: "str"


class AddScriptToEvaluateOnLoadReturns(TypedDict):
    identifier: "ScriptIdentifier"
    """Identifier of the added script."""


class RemoveScriptToEvaluateOnLoadParameters(TypedDict):
    identifier: "ScriptIdentifier"


class AddScriptToEvaluateOnNewDocumentParameters(TypedDict):
    source: "str"


class AddScriptToEvaluateOnNewDocumentReturns(TypedDict):
    identifier: "ScriptIdentifier"
    """Identifier of the added script."""


class RemoveScriptToEvaluateOnNewDocumentParameters(TypedDict):
    identifier: "ScriptIdentifier"


class SetAutoAttachToCreatedPagesParameters(TypedDict):
    autoAttach: "bool"
    """If true, browser will open a new inspector window for every page created from this one."""


class SetLifecycleEventsEnabledParameters(TypedDict):
    enabled: "bool"
    """If true, starts emitting lifecycle events."""


class ReloadParameters(TypedDict, total=False):
    ignoreCache: "bool"
    """If true, browser cache is ignored (as if the user pressed Shift+refresh)."""
    scriptToEvaluateOnLoad: "str"
    """If set, the script will be injected into all frames of the inspected page after reload."""


class SetAdBlockingEnabledParameters(TypedDict):
    enabled: "bool"
    """Whether to block ads."""


class NavigateParameters(TypedDict):
    url: "str"
    """URL to navigate the page to."""
    referrer: "NotRequired[str]"
    """Referrer URL."""
    transitionType: "NotRequired[TransitionType]"
    """Intended transition type."""


class NavigateReturns(TypedDict):
    frameId: "FrameId"
    """Frame id that has navigated (or failed to navigate)"""
    loaderId: "LoaderId"
    """Loader identifier."""
    errorText: "str"
    """User friendly error message, present if and only if navigation has failed."""


class GetNavigationHistoryReturns(TypedDict):
    currentIndex: "int"
    """Index of the current navigation history entry."""
    entries: "List[NavigationEntry]"
    """Array of navigation history entries."""


class NavigateToHistoryEntryParameters(TypedDict):
    entryId: "int"
    """Unique id of the entry to navigate to."""


class GetCookiesReturns(TypedDict):
    cookies: "List[Cookie]"
    """Array of cookie objects."""


class DeleteCookieParameters(TypedDict):
    cookieName: "str"
    """Name of the cookie to remove."""
    url: "str"
    """URL to match cooke domain and path."""


class GetResourceTreeReturns(TypedDict):
    frameTree: "FrameResourceTree"
    """Present frame / resource tree structure."""


class GetFrameTreeReturns(TypedDict):
    frameTree: "FrameTree"
    """Present frame tree structure."""


class GetResourceContentParameters(TypedDict):
    frameId: "FrameId"
    """Frame id to get resource for."""
    url: "str"
    """URL of the resource to get content for."""


class GetResourceContentReturns(TypedDict):
    content: "str"
    """Resource content."""
    base64Encoded: "bool"
    """True, if content was served as base64."""


class SearchInResourceParameters(TypedDict):
    frameId: "FrameId"
    """Frame id for resource to search in."""
    url: "str"
    """URL of the resource to search in."""
    query: "str"
    """String to search for."""
    caseSensitive: "NotRequired[bool]"
    """If true, search is case sensitive."""
    isRegex: "NotRequired[bool]"
    """If true, treats string parameter as regex."""


class SearchInResourceReturns(TypedDict):
    result: "List[SearchMatch]"
    """List of search matches."""


class SetDocumentContentParameters(TypedDict):
    frameId: "FrameId"
    """Frame id to set HTML for."""
    html: "str"
    """HTML content to set."""


class SetDeviceMetricsOverrideParameters(TypedDict):
    width: "int"
    """Overriding width value in pixels (minimum 0, maximum 10000000). 0 disables the override."""
    height: "int"
    """Overriding height value in pixels (minimum 0, maximum 10000000). 0 disables the override."""
    deviceScaleFactor: "float"
    """Overriding device scale factor value. 0 disables the override."""
    mobile: "bool"
    """Whether to emulate mobile device. This includes viewport meta tag, overlay scrollbars, text autosizing and more."""
    scale: "NotRequired[float]"
    """Scale to apply to resulting view image."""
    screenWidth: "NotRequired[int]"
    """Overriding screen width value in pixels (minimum 0, maximum 10000000)."""
    screenHeight: "NotRequired[int]"
    """Overriding screen height value in pixels (minimum 0, maximum 10000000)."""
    positionX: "NotRequired[int]"
    """Overriding view X position on screen in pixels (minimum 0, maximum 10000000)."""
    positionY: "NotRequired[int]"
    """Overriding view Y position on screen in pixels (minimum 0, maximum 10000000)."""
    dontSetVisibleSize: "NotRequired[bool]"
    """Do not set visible view size, rely upon explicit setVisibleSize call."""
    screenOrientation: "NotRequired[ScreenOrientation]"
    """Screen orientation override."""
    viewport: "NotRequired[Viewport]"
    """The viewport dimensions and scale. If not set, the override is cleared."""


class SetGeolocationOverrideParameters(TypedDict, total=False):
    latitude: "float"
    """Mock latitude"""
    longitude: "float"
    """Mock longitude"""
    accuracy: "float"
    """Mock accuracy"""


class SetDeviceOrientationOverrideParameters(TypedDict):
    alpha: "float"
    """Mock alpha"""
    beta: "float"
    """Mock beta"""
    gamma: "float"
    """Mock gamma"""


class SetTouchEmulationEnabledParameters(TypedDict):
    enabled: "bool"
    """Whether the touch event emulation should be enabled."""
    configuration: "NotRequired[str]"
    """Touch/gesture events configuration. Default: current platform."""


class CaptureScreenshotParameters(TypedDict, total=False):
    format: "str"
    """Image compression format (defaults to png)."""
    quality: "int"
    """Compression quality from range [0..100] (jpeg only)."""
    clip: "Viewport"
    """Capture the screenshot of a given region only."""
    fromSurface: "bool"
    """Capture the screenshot from the surface, rather than the view. Defaults to true."""


class CaptureScreenshotReturns(TypedDict):
    data: "str"
    """Base64-encoded image data."""


class PrintToPDFParameters(TypedDict, total=False):
    landscape: "bool"
    """Paper orientation. Defaults to false."""
    displayHeaderFooter: "bool"
    """Display header and footer. Defaults to false."""
    printBackground: "bool"
    """Print background graphics. Defaults to false."""
    scale: "float"
    """Scale of the webpage rendering. Defaults to 1."""
    paperWidth: "float"
    """Paper width in inches. Defaults to 8.5 inches."""
    paperHeight: "float"
    """Paper height in inches. Defaults to 11 inches."""
    marginTop: "float"
    """Top margin in inches. Defaults to 1cm (~0.4 inches)."""
    marginBottom: "float"
    """Bottom margin in inches. Defaults to 1cm (~0.4 inches)."""
    marginLeft: "float"
    """Left margin in inches. Defaults to 1cm (~0.4 inches)."""
    marginRight: "float"
    """Right margin in inches. Defaults to 1cm (~0.4 inches)."""
    pageRanges: "str"
    """Paper ranges to print, e.g., '1-5, 8, 11-13'. Defaults to the empty string, which means print all pages."""
    ignoreInvalidPageRanges: "bool"
    """Whether to silently ignore invalid but successfully parsed page ranges, such as '3-2'. Defaults to false."""


class PrintToPDFReturns(TypedDict):
    data: "str"
    """Base64-encoded pdf data."""


class StartScreencastParameters(TypedDict, total=False):
    format: "str"
    """Image compression format."""
    quality: "int"
    """Compression quality from range [0..100]."""
    maxWidth: "int"
    """Maximum screenshot width."""
    maxHeight: "int"
    """Maximum screenshot height."""
    everyNthFrame: "int"
    """Send every n-th frame."""


class ScreencastFrameAckParameters(TypedDict):
    sessionId: "int"
    """Frame number."""


class HandleJavaScriptDialogParameters(TypedDict):
    accept: "bool"
    """Whether to accept or dismiss the dialog."""
    promptText: "NotRequired[str]"
    """The text to enter into the dialog prompt before accepting. Used only if this is a prompt dialog."""


class GetAppManifestReturns(TypedDict):
    url: "str"
    """Manifest location."""
    errors: "List[AppManifestError]"
    data: "str"
    """Manifest content."""


class GetLayoutMetricsReturns(TypedDict):
    layoutViewport: "LayoutViewport"
    """Metrics relating to the layout viewport."""
    visualViewport: "VisualViewport"
    """Metrics relating to the visual viewport."""
    contentSize: "Rect"
    """Size of scrollable area."""


class CreateIsolatedWorldParameters(TypedDict):
    frameId: "FrameId"
    """Id of the frame in which the isolated world should be created."""
    worldName: "NotRequired[str]"
    """An optional name which is reported in the Execution Context."""
    grantUniveralAccess: "NotRequired[bool]"
    """Whether or not universal access should be granted to the isolated world. This is a powerful option, use with caution."""


class CreateIsolatedWorldReturns(TypedDict):
    executionContextId: "ExecutionContextId"
    """Execution context of the isolated world."""


class SetDownloadBehaviorParameters(TypedDict):
    behavior: "str"
    """Whether to allow all or deny all download requests, or use default Chrome behavior if available (otherwise deny)."""
    downloadPath: "NotRequired[str]"
    """The default path to save downloaded files to. This is requred if behavior is set to 'allow'"""
