# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Page Domain Events"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..network.types import LoaderId
    from ..network.types import MonotonicTime
    from ..runtime.types import StackTrace
    from .types import DialogType
    from .types import Frame
    from .types import FrameId
    from .types import ScreencastFrameMetadata


class DomContentEventFiredEvent(TypedDict):
    timestamp: "MonotonicTime"


class LoadEventFiredEvent(TypedDict):
    timestamp: "MonotonicTime"


"""Fired for top level page lifecycle events such as navigation, load, paint, etc."""


class LifecycleEventEvent(TypedDict):
    frameId: "FrameId"
    """Id of the frame."""
    loaderId: "LoaderId"
    """Loader identifier. Empty string if the request is fetched from worker."""
    name: "str"
    timestamp: "MonotonicTime"


"""Fired when frame has been attached to its parent."""


class FrameAttachedEvent(TypedDict):
    frameId: "FrameId"
    """Id of the frame that has been attached."""
    parentFrameId: "FrameId"
    """Parent frame identifier."""
    stack: "NotRequired[StackTrace]"
    """JavaScript stack trace of when frame was attached, only set if frame initiated from script."""


"""Fired once navigation of the frame has completed. Frame is now associated with the new loader."""


class FrameNavigatedEvent(TypedDict):
    frame: "Frame"
    """Frame object."""


"""Fired when frame has been detached from its parent."""


class FrameDetachedEvent(TypedDict):
    frameId: "FrameId"
    """Id of the frame that has been detached."""


"""Fired when frame has started loading."""


class FrameStartedLoadingEvent(TypedDict):
    frameId: "FrameId"
    """Id of the frame that has started loading."""


"""Fired when frame has stopped loading."""


class FrameStoppedLoadingEvent(TypedDict):
    frameId: "FrameId"
    """Id of the frame that has stopped loading."""


"""Fired when frame schedules a potential navigation."""


class FrameScheduledNavigationEvent(TypedDict):
    frameId: "FrameId"
    """Id of the frame that has scheduled a navigation."""
    delay: "float"
    """Delay (in seconds) until the navigation is scheduled to begin. The navigation is not guaranteed to start."""
    reason: "str"
    """The reason for the navigation."""
    url: "str"
    """The destination URL for the scheduled navigation."""


"""Fired when frame no longer has a scheduled navigation."""


class FrameClearedScheduledNavigationEvent(TypedDict):
    frameId: "FrameId"
    """Id of the frame that has cleared its scheduled navigation."""


class FrameResizedEvent(TypedDict):
    pass


"""Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) is about to open."""


class JavascriptDialogOpeningEvent(TypedDict):
    url: "str"
    """Frame url."""
    message: "str"
    """Message that will be displayed by the dialog."""
    type: "DialogType"
    """Dialog type."""
    defaultPrompt: "NotRequired[str]"
    """Default dialog prompt."""


"""Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) has been closed."""


class JavascriptDialogClosedEvent(TypedDict):
    result: "bool"
    """Whether dialog was confirmed."""
    userInput: "str"
    """User input in case of prompt."""


"""Compressed image data requested by the <code>startScreencast</code>."""


class ScreencastFrameEvent(TypedDict):
    data: "str"
    """Base64-encoded compressed image."""
    metadata: "ScreencastFrameMetadata"
    """Screencast frame metadata."""
    sessionId: "int"
    """Frame number."""


"""Fired when the page with currently enabled screencast was shown or hidden </code>."""


class ScreencastVisibilityChangedEvent(TypedDict):
    visible: "bool"
    """True if the page is visible."""


"""Fired when interstitial page was shown"""


class InterstitialShownEvent(TypedDict):
    pass


"""Fired when interstitial page was hidden"""


class InterstitialHiddenEvent(TypedDict):
    pass


"""Fired when a new window is going to be opened, via window.open(), link click, form submission, etc."""


class WindowOpenEvent(TypedDict):
    url: "str"
    """The URL for the new window."""
    windowName: "str"
    """Window name."""
    windowFeatures: "List[str]"
    """An array of enabled window features."""
    userGesture: "bool"
    """Whether or not it was triggered by user gesture."""
