# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Page Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import AddScriptToEvaluateOnLoadParameters
    from .commands import AddScriptToEvaluateOnLoadReturns
    from .commands import AddScriptToEvaluateOnNewDocumentParameters
    from .commands import AddScriptToEvaluateOnNewDocumentReturns
    from .commands import CaptureScreenshotParameters
    from .commands import CaptureScreenshotReturns
    from .commands import CreateIsolatedWorldParameters
    from .commands import CreateIsolatedWorldReturns
    from .commands import DeleteCookieParameters
    from .commands import GetAppManifestReturns
    from .commands import GetCookiesReturns
    from .commands import GetFrameTreeReturns
    from .commands import GetLayoutMetricsReturns
    from .commands import GetNavigationHistoryReturns
    from .commands import GetResourceContentParameters
    from .commands import GetResourceContentReturns
    from .commands import GetResourceTreeReturns
    from .commands import HandleJavaScriptDialogParameters
    from .commands import NavigateParameters
    from .commands import NavigateReturns
    from .commands import NavigateToHistoryEntryParameters
    from .commands import PrintToPDFParameters
    from .commands import PrintToPDFReturns
    from .commands import ReloadParameters
    from .commands import RemoveScriptToEvaluateOnLoadParameters
    from .commands import RemoveScriptToEvaluateOnNewDocumentParameters
    from .commands import ScreencastFrameAckParameters
    from .commands import SearchInResourceParameters
    from .commands import SearchInResourceReturns
    from .commands import SetAdBlockingEnabledParameters
    from .commands import SetAutoAttachToCreatedPagesParameters
    from .commands import SetDeviceMetricsOverrideParameters
    from .commands import SetDeviceOrientationOverrideParameters
    from .commands import SetDocumentContentParameters
    from .commands import SetDownloadBehaviorParameters
    from .commands import SetGeolocationOverrideParameters
    from .commands import SetLifecycleEventsEnabledParameters
    from .commands import SetTouchEmulationEnabledParameters
    from .commands import StartScreencastParameters


class PageClient:
    """Client for Page domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def enable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enables page domain notifications."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.enable",
                params=params,
                session_id=session_id,
            ),
        )

    async def disable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Disables page domain notifications."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.disable",
                params=params,
                session_id=session_id,
            ),
        )

    async def addScriptToEvaluateOnLoad(
        self,
        params: "AddScriptToEvaluateOnLoadParameters",
        session_id: Optional[str] = None,
    ) -> "AddScriptToEvaluateOnLoadReturns":
        """Deprecated, please use addScriptToEvaluateOnNewDocument instead."""
        return cast(
            "AddScriptToEvaluateOnLoadReturns",
            await self._client.send_raw(
                method="Page.addScriptToEvaluateOnLoad",
                params=params,
                session_id=session_id,
            ),
        )

    async def removeScriptToEvaluateOnLoad(
        self,
        params: "RemoveScriptToEvaluateOnLoadParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Deprecated, please use removeScriptToEvaluateOnNewDocument instead."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.removeScriptToEvaluateOnLoad",
                params=params,
                session_id=session_id,
            ),
        )

    async def addScriptToEvaluateOnNewDocument(
        self,
        params: "AddScriptToEvaluateOnNewDocumentParameters",
        session_id: Optional[str] = None,
    ) -> "AddScriptToEvaluateOnNewDocumentReturns":
        """Evaluates given script in every frame upon creation (before loading frame's scripts)."""
        return cast(
            "AddScriptToEvaluateOnNewDocumentReturns",
            await self._client.send_raw(
                method="Page.addScriptToEvaluateOnNewDocument",
                params=params,
                session_id=session_id,
            ),
        )

    async def removeScriptToEvaluateOnNewDocument(
        self,
        params: "RemoveScriptToEvaluateOnNewDocumentParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Removes given script from the list."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.removeScriptToEvaluateOnNewDocument",
                params=params,
                session_id=session_id,
            ),
        )

    async def setAutoAttachToCreatedPages(
        self,
        params: "SetAutoAttachToCreatedPagesParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Controls whether browser will open a new inspector window for connected pages."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.setAutoAttachToCreatedPages",
                params=params,
                session_id=session_id,
            ),
        )

    async def setLifecycleEventsEnabled(
        self,
        params: "SetLifecycleEventsEnabledParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Controls whether page will emit lifecycle events."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.setLifecycleEventsEnabled",
                params=params,
                session_id=session_id,
            ),
        )

    async def reload(
        self,
        params: Optional["ReloadParameters"] = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Reloads given page optionally ignoring the cache."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.reload",
                params=params,
                session_id=session_id,
            ),
        )

    async def setAdBlockingEnabled(
        self,
        params: "SetAdBlockingEnabledParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enable Chrome's experimental ad filter on all sites."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.setAdBlockingEnabled",
                params=params,
                session_id=session_id,
            ),
        )

    async def navigate(
        self,
        params: "NavigateParameters",
        session_id: Optional[str] = None,
    ) -> "NavigateReturns":
        """Navigates current page to the given URL."""
        return cast(
            "NavigateReturns",
            await self._client.send_raw(
                method="Page.navigate",
                params=params,
                session_id=session_id,
            ),
        )

    async def stopLoading(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Force the page stop all navigations and pending resource fetches."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.stopLoading",
                params=params,
                session_id=session_id,
            ),
        )

    async def getNavigationHistory(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetNavigationHistoryReturns":
        """Returns navigation history for the current page."""
        return cast(
            "GetNavigationHistoryReturns",
            await self._client.send_raw(
                method="Page.getNavigationHistory",
                params=params,
                session_id=session_id,
            ),
        )

    async def navigateToHistoryEntry(
        self,
        params: "NavigateToHistoryEntryParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Navigates current page to the given history entry."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.navigateToHistoryEntry",
                params=params,
                session_id=session_id,
            ),
        )

    async def getCookies(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetCookiesReturns":
        """Returns all browser cookies. Depending on the backend support, will return detailed cookie information in the <code>cookies</code> field."""
        return cast(
            "GetCookiesReturns",
            await self._client.send_raw(
                method="Page.getCookies",
                params=params,
                session_id=session_id,
            ),
        )

    async def deleteCookie(
        self,
        params: "DeleteCookieParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Deletes browser cookie with given name, domain and path."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.deleteCookie",
                params=params,
                session_id=session_id,
            ),
        )

    async def getResourceTree(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetResourceTreeReturns":
        """Returns present frame / resource tree structure."""
        return cast(
            "GetResourceTreeReturns",
            await self._client.send_raw(
                method="Page.getResourceTree",
                params=params,
                session_id=session_id,
            ),
        )

    async def getFrameTree(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetFrameTreeReturns":
        """Returns present frame tree structure."""
        return cast(
            "GetFrameTreeReturns",
            await self._client.send_raw(
                method="Page.getFrameTree",
                params=params,
                session_id=session_id,
            ),
        )

    async def getResourceContent(
        self,
        params: "GetResourceContentParameters",
        session_id: Optional[str] = None,
    ) -> "GetResourceContentReturns":
        """Returns content of the given resource."""
        return cast(
            "GetResourceContentReturns",
            await self._client.send_raw(
                method="Page.getResourceContent",
                params=params,
                session_id=session_id,
            ),
        )

    async def searchInResource(
        self,
        params: "SearchInResourceParameters",
        session_id: Optional[str] = None,
    ) -> "SearchInResourceReturns":
        """Searches for given string in resource content."""
        return cast(
            "SearchInResourceReturns",
            await self._client.send_raw(
                method="Page.searchInResource",
                params=params,
                session_id=session_id,
            ),
        )

    async def setDocumentContent(
        self,
        params: "SetDocumentContentParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Sets given markup as the document's HTML."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.setDocumentContent",
                params=params,
                session_id=session_id,
            ),
        )

    async def setDeviceMetricsOverride(
        self,
        params: "SetDeviceMetricsOverrideParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Overrides the values of device screen dimensions (window.screen.width, window.screen.height, window.innerWidth, window.innerHeight, and \"device-width\"/\"device-height\"-related CSS media query results)."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.setDeviceMetricsOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def clearDeviceMetricsOverride(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Clears the overriden device metrics."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.clearDeviceMetricsOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def setGeolocationOverride(
        self,
        params: Optional["SetGeolocationOverrideParameters"] = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Overrides the Geolocation Position or Error. Omitting any of the parameters emulates position unavailable."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.setGeolocationOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def clearGeolocationOverride(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Clears the overriden Geolocation Position and Error."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.clearGeolocationOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def setDeviceOrientationOverride(
        self,
        params: "SetDeviceOrientationOverrideParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Overrides the Device Orientation."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.setDeviceOrientationOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def clearDeviceOrientationOverride(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Clears the overridden Device Orientation."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.clearDeviceOrientationOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def setTouchEmulationEnabled(
        self,
        params: "SetTouchEmulationEnabledParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Toggles mouse event-based touch event emulation."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.setTouchEmulationEnabled",
                params=params,
                session_id=session_id,
            ),
        )

    async def captureScreenshot(
        self,
        params: Optional["CaptureScreenshotParameters"] = None,
        session_id: Optional[str] = None,
    ) -> "CaptureScreenshotReturns":
        """Capture page screenshot."""
        return cast(
            "CaptureScreenshotReturns",
            await self._client.send_raw(
                method="Page.captureScreenshot",
                params=params,
                session_id=session_id,
            ),
        )

    async def printToPDF(
        self,
        params: Optional["PrintToPDFParameters"] = None,
        session_id: Optional[str] = None,
    ) -> "PrintToPDFReturns":
        """Print page as PDF."""
        return cast(
            "PrintToPDFReturns",
            await self._client.send_raw(
                method="Page.printToPDF",
                params=params,
                session_id=session_id,
            ),
        )

    async def startScreencast(
        self,
        params: Optional["StartScreencastParameters"] = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Starts sending each frame using the <code>screencastFrame</code> event."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.startScreencast",
                params=params,
                session_id=session_id,
            ),
        )

    async def stopScreencast(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Stops sending each frame in the <code>screencastFrame</code>."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.stopScreencast",
                params=params,
                session_id=session_id,
            ),
        )

    async def screencastFrameAck(
        self,
        params: "ScreencastFrameAckParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Acknowledges that a screencast frame has been received by the frontend."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.screencastFrameAck",
                params=params,
                session_id=session_id,
            ),
        )

    async def handleJavaScriptDialog(
        self,
        params: "HandleJavaScriptDialogParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Accepts or dismisses a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload)."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.handleJavaScriptDialog",
                params=params,
                session_id=session_id,
            ),
        )

    async def getAppManifest(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetAppManifestReturns":
        return cast(
            "GetAppManifestReturns",
            await self._client.send_raw(
                method="Page.getAppManifest",
                params=params,
                session_id=session_id,
            ),
        )

    async def getLayoutMetrics(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetLayoutMetricsReturns":
        """Returns metrics relating to the layouting of the page, such as viewport bounds/scale."""
        return cast(
            "GetLayoutMetricsReturns",
            await self._client.send_raw(
                method="Page.getLayoutMetrics",
                params=params,
                session_id=session_id,
            ),
        )

    async def createIsolatedWorld(
        self,
        params: "CreateIsolatedWorldParameters",
        session_id: Optional[str] = None,
    ) -> "CreateIsolatedWorldReturns":
        """Creates an isolated world for the given frame."""
        return cast(
            "CreateIsolatedWorldReturns",
            await self._client.send_raw(
                method="Page.createIsolatedWorld",
                params=params,
                session_id=session_id,
            ),
        )

    async def bringToFront(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Brings page to front (activates tab)."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.bringToFront",
                params=params,
                session_id=session_id,
            ),
        )

    async def setDownloadBehavior(
        self,
        params: "SetDownloadBehaviorParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Set the behavior when downloading a file."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Page.setDownloadBehavior",
                params=params,
                session_id=session_id,
            ),
        )
