# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Page Domain Event Registration"""

from typing import Callable, Optional

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import (
        DomContentEventFiredEvent,
        FrameAttachedEvent,
        FrameClearedScheduledNavigationEvent,
        FrameDetachedEvent,
        FrameNavigatedEvent,
        FrameResizedEvent,
        FrameScheduledNavigationEvent,
        FrameStartedLoadingEvent,
        FrameStoppedLoadingEvent,
        InterstitialHiddenEvent,
        InterstitialShownEvent,
        JavascriptDialogClosedEvent,
        JavascriptDialogOpeningEvent,
        LifecycleEventEvent,
        LoadEventFiredEvent,
        ScreencastFrameEvent,
        ScreencastVisibilityChangedEvent,
        WindowOpenEvent,
    )


class PageRegistration:
    """Event registration interface for Page domain."""

    def __init__(self, registry: "EventRegistry"):
        self._registry = registry
        self._domain = "Page"

    def domContentEventFired(
        self,
        callback: Callable[["DomContentEventFiredEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for domContentEventFired events.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.domContentEventFired", callback)

    def loadEventFired(
        self,
        callback: Callable[["LoadEventFiredEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for loadEventFired events.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.loadEventFired", callback)

    def lifecycleEvent(
        self,
        callback: Callable[["LifecycleEventEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for lifecycleEvent events.

        Fired for top level page lifecycle events such as navigation, load, paint, etc.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.lifecycleEvent", callback)

    def frameAttached(
        self,
        callback: Callable[["FrameAttachedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for frameAttached events.

        Fired when frame has been attached to its parent.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.frameAttached", callback)

    def frameNavigated(
        self,
        callback: Callable[["FrameNavigatedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for frameNavigated events.

        Fired once navigation of the frame has completed. Frame is now associated with the new loader.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.frameNavigated", callback)

    def frameDetached(
        self,
        callback: Callable[["FrameDetachedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for frameDetached events.

        Fired when frame has been detached from its parent.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.frameDetached", callback)

    def frameStartedLoading(
        self,
        callback: Callable[["FrameStartedLoadingEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for frameStartedLoading events.

        Fired when frame has started loading.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.frameStartedLoading", callback)

    def frameStoppedLoading(
        self,
        callback: Callable[["FrameStoppedLoadingEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for frameStoppedLoading events.

        Fired when frame has stopped loading.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.frameStoppedLoading", callback)

    def frameScheduledNavigation(
        self,
        callback: Callable[["FrameScheduledNavigationEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for frameScheduledNavigation events.

        Fired when frame schedules a potential navigation.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.frameScheduledNavigation", callback)

    def frameClearedScheduledNavigation(
        self,
        callback: Callable[
            ["FrameClearedScheduledNavigationEvent", Optional[str]], None
        ],
    ) -> None:
        """
        Register a callback for frameClearedScheduledNavigation events.

        Fired when frame no longer has a scheduled navigation.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.frameClearedScheduledNavigation", callback)

    def frameResized(
        self,
        callback: Callable[["FrameResizedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for frameResized events.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.frameResized", callback)

    def javascriptDialogOpening(
        self,
        callback: Callable[["JavascriptDialogOpeningEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for javascriptDialogOpening events.

        Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) is about to open.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.javascriptDialogOpening", callback)

    def javascriptDialogClosed(
        self,
        callback: Callable[["JavascriptDialogClosedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for javascriptDialogClosed events.

        Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) has been closed.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.javascriptDialogClosed", callback)

    def screencastFrame(
        self,
        callback: Callable[["ScreencastFrameEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for screencastFrame events.

        Compressed image data requested by the <code>startScreencast</code>.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.screencastFrame", callback)

    def screencastVisibilityChanged(
        self,
        callback: Callable[["ScreencastVisibilityChangedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for screencastVisibilityChanged events.

        Fired when the page with currently enabled screencast was shown or hidden </code>.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.screencastVisibilityChanged", callback)

    def interstitialShown(
        self,
        callback: Callable[["InterstitialShownEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for interstitialShown events.

        Fired when interstitial page was shown

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.interstitialShown", callback)

    def interstitialHidden(
        self,
        callback: Callable[["InterstitialHiddenEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for interstitialHidden events.

        Fired when interstitial page was hidden

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.interstitialHidden", callback)

    def windowOpen(
        self,
        callback: Callable[["WindowOpenEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for windowOpen events.

        Fired when a new window is going to be opened, via window.open(), link click, form submission, etc.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Page.windowOpen", callback)
