# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Page Domain Types"""

from typing import List
from typing_extensions import Literal
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..network.types import LoaderId
    from ..network.types import TimeSinceEpoch

ResourceType = Literal[
    "Document",
    "Stylesheet",
    "Image",
    "Media",
    "Font",
    "Script",
    "TextTrack",
    "XHR",
    "Fetch",
    "EventSource",
    "WebSocket",
    "Manifest",
    "Other",
]
"""Resource type as it was perceived by the rendering engine."""


FrameId = str
"""Unique frame identifier."""


class Frame(TypedDict):
    """Information about the Frame on the page."""

    id: "str"
    """Frame unique identifier."""
    parentId: "NotRequired[str]"
    """Parent frame identifier."""
    loaderId: "LoaderId"
    """Identifier of the loader associated with this frame."""
    name: "NotRequired[str]"
    """Frame's name as specified in the tag."""
    url: "str"
    """Frame document's URL."""
    securityOrigin: "str"
    """Frame document's security origin."""
    mimeType: "str"
    """Frame document's mimeType as determined by the browser."""
    unreachableUrl: "NotRequired[str]"
    """If the frame failed to load, this contains the URL that could not be loaded."""


class FrameResource(TypedDict):
    """Information about the Resource on the page."""

    url: "str"
    """Resource URL."""
    type: "ResourceType"
    """Type of this resource."""
    mimeType: "str"
    """Resource mimeType as determined by the browser."""
    lastModified: "NotRequired[TimeSinceEpoch]"
    """last-modified timestamp as reported by server."""
    contentSize: "NotRequired[float]"
    """Resource content size."""
    failed: "NotRequired[bool]"
    """True if the resource failed to load."""
    canceled: "NotRequired[bool]"
    """True if the resource was canceled during loading."""


class FrameResourceTree(TypedDict):
    """Information about the Frame hierarchy along with their cached resources."""

    frame: "Frame"
    """Frame information for this tree item."""
    childFrames: "NotRequired[List[FrameResourceTree]]"
    """Child frames."""
    resources: "List[FrameResource]"
    """Information about frame resources."""


class FrameTree(TypedDict):
    """Information about the Frame hierarchy."""

    frame: "Frame"
    """Frame information for this tree item."""
    childFrames: "NotRequired[List[FrameTree]]"
    """Child frames."""


ScriptIdentifier = str
"""Unique script identifier."""


TransitionType = Literal[
    "link",
    "typed",
    "auto_bookmark",
    "auto_subframe",
    "manual_subframe",
    "generated",
    "auto_toplevel",
    "form_submit",
    "reload",
    "keyword",
    "keyword_generated",
    "other",
]
"""Transition type."""


class NavigationEntry(TypedDict):
    """Navigation history entry."""

    id: "int"
    """Unique id of the navigation history entry."""
    url: "str"
    """URL of the navigation history entry."""
    userTypedURL: "str"
    """URL that the user typed in the url bar."""
    title: "str"
    """Title of the navigation history entry."""
    transitionType: "TransitionType"
    """Transition type."""


class ScreencastFrameMetadata(TypedDict):
    """Screencast frame metadata."""

    offsetTop: "float"
    """Top offset in DIP."""
    pageScaleFactor: "float"
    """Page scale factor."""
    deviceWidth: "float"
    """Device screen width in DIP."""
    deviceHeight: "float"
    """Device screen height in DIP."""
    scrollOffsetX: "float"
    """Position of horizontal scroll in CSS pixels."""
    scrollOffsetY: "float"
    """Position of vertical scroll in CSS pixels."""
    timestamp: "NotRequired[TimeSinceEpoch]"
    """Frame swap timestamp."""


DialogType = Literal["alert", "confirm", "prompt", "beforeunload"]
"""Javascript dialog type."""


class AppManifestError(TypedDict):
    """Error while paring app manifest."""

    message: "str"
    """Error message."""
    critical: "int"
    """If criticial, this is a non-recoverable parse error."""
    line: "int"
    """Error line."""
    column: "int"
    """Error column."""


class LayoutViewport(TypedDict):
    """Layout viewport position and dimensions."""

    pageX: "int"
    """Horizontal offset relative to the document (CSS pixels)."""
    pageY: "int"
    """Vertical offset relative to the document (CSS pixels)."""
    clientWidth: "int"
    """Width (CSS pixels), excludes scrollbar if present."""
    clientHeight: "int"
    """Height (CSS pixels), excludes scrollbar if present."""


class VisualViewport(TypedDict):
    """Visual viewport position, dimensions, and scale."""

    offsetX: "float"
    """Horizontal offset relative to the layout viewport (CSS pixels)."""
    offsetY: "float"
    """Vertical offset relative to the layout viewport (CSS pixels)."""
    pageX: "float"
    """Horizontal offset relative to the document (CSS pixels)."""
    pageY: "float"
    """Vertical offset relative to the document (CSS pixels)."""
    clientWidth: "float"
    """Width (CSS pixels), excludes scrollbar if present."""
    clientHeight: "float"
    """Height (CSS pixels), excludes scrollbar if present."""
    scale: "float"
    """Scale relative to the ideal viewport (size at width=device-width)."""


class Viewport(TypedDict):
    """Viewport for capturing screenshot."""

    x: "float"
    """X offset in CSS pixels."""
    y: "float"
    """Y offset in CSS pixels"""
    width: "float"
    """Rectangle width in CSS pixels"""
    height: "float"
    """Rectangle height in CSS pixels"""
    scale: "float"
    """Page scale factor."""
