# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP ApplicationCache Domain Commands"""

from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..page.types import FrameId
    from .types import ApplicationCache
    from .types import FrameWithManifest


class GetFramesWithManifestsReturns(TypedDict):
    frameIds: "List[FrameWithManifest]"
    """Array of frame identifiers with manifest urls for each frame containing a document associated with some application cache."""


class GetManifestForFrameParameters(TypedDict):
    frameId: "FrameId"
    """Identifier of the frame containing document whose manifest is retrieved."""


class GetManifestForFrameReturns(TypedDict):
    manifestURL: "str"
    """Manifest URL for document in the given frame."""


class GetApplicationCacheForFrameParameters(TypedDict):
    frameId: "FrameId"
    """Identifier of the frame containing document whose application cache is retrieved."""


class GetApplicationCacheForFrameReturns(TypedDict):
    applicationCache: "ApplicationCache"
    """Relevant application cache data for the document in given frame."""
