# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP ApplicationCache Domain Events"""

from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..page.types import FrameId


class ApplicationCacheStatusUpdatedEvent(TypedDict):
    frameId: "FrameId"
    """Identifier of the frame containing document whose application cache updated status."""
    manifestURL: "str"
    """Manifest URL."""
    status: "int"
    """Updated application cache status."""


class NetworkStateUpdatedEvent(TypedDict):
    isNowOnline: "bool"
