# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP ApplicationCache Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import GetApplicationCacheForFrameParameters
    from .commands import GetApplicationCacheForFrameReturns
    from .commands import GetFramesWithManifestsReturns
    from .commands import GetManifestForFrameParameters
    from .commands import GetManifestForFrameReturns


class ApplicationCacheClient:
    """Client for ApplicationCache domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def getFramesWithManifests(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetFramesWithManifestsReturns":
        """Returns array of frame identifiers with manifest urls for each frame containing a document associated with some application cache."""
        return cast(
            "GetFramesWithManifestsReturns",
            await self._client.send_raw(
                method="ApplicationCache.getFramesWithManifests",
                params=params,
                session_id=session_id,
            ),
        )

    async def enable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enables application cache domain notifications."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="ApplicationCache.enable",
                params=params,
                session_id=session_id,
            ),
        )

    async def getManifestForFrame(
        self,
        params: "GetManifestForFrameParameters",
        session_id: Optional[str] = None,
    ) -> "GetManifestForFrameReturns":
        """Returns manifest URL for document in the given frame."""
        return cast(
            "GetManifestForFrameReturns",
            await self._client.send_raw(
                method="ApplicationCache.getManifestForFrame",
                params=params,
                session_id=session_id,
            ),
        )

    async def getApplicationCacheForFrame(
        self,
        params: "GetApplicationCacheForFrameParameters",
        session_id: Optional[str] = None,
    ) -> "GetApplicationCacheForFrameReturns":
        """Returns relevant application cache data for the document in given frame."""
        return cast(
            "GetApplicationCacheForFrameReturns",
            await self._client.send_raw(
                method="ApplicationCache.getApplicationCacheForFrame",
                params=params,
                session_id=session_id,
            ),
        )
