# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP ApplicationCache Domain Event Registration"""

from typing import Callable, Optional

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import ApplicationCacheStatusUpdatedEvent, NetworkStateUpdatedEvent


class ApplicationCacheRegistration:
    """Event registration interface for ApplicationCache domain."""

    def __init__(self, registry: "EventRegistry"):
        self._registry = registry
        self._domain = "ApplicationCache"

    def applicationCacheStatusUpdated(
        self,
        callback: Callable[["ApplicationCacheStatusUpdatedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for applicationCacheStatusUpdated events.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register(
            "ApplicationCache.applicationCacheStatusUpdated", callback
        )

    def networkStateUpdated(
        self,
        callback: Callable[["NetworkStateUpdatedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for networkStateUpdated events.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("ApplicationCache.networkStateUpdated", callback)
