# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP ApplicationCache Domain Types"""

from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..page.types import FrameId


class ApplicationCacheResource(TypedDict):
    """Detailed application cache resource information."""

    url: "str"
    """Resource url."""
    size: "int"
    """Resource size."""
    type: "str"
    """Resource type."""


class ApplicationCache(TypedDict):
    """Detailed application cache information."""

    manifestURL: "str"
    """Manifest URL."""
    size: "float"
    """Application cache size."""
    creationTime: "float"
    """Application cache creation time."""
    updateTime: "float"
    """Application cache update time."""
    resources: "List[ApplicationCacheResource]"
    """Application cache resources."""


class FrameWithManifest(TypedDict):
    """Frame identifier - manifest URL pair."""

    frameId: "FrameId"
    """Frame identifier."""
    manifestURL: "str"
    """Manifest URL."""
    status: "int"
    """Application cache status."""
