# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Storage Domain Commands"""

from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import UsageForType


class ClearDataForOriginParameters(TypedDict):
    origin: "str"
    """Security origin."""
    storageTypes: "str"
    """Comma separated origin names."""


class GetUsageAndQuotaParameters(TypedDict):
    origin: "str"
    """Security origin."""


class GetUsageAndQuotaReturns(TypedDict):
    usage: "float"
    """Storage usage (bytes)."""
    quota: "float"
    """Storage quota (bytes)."""
    usageBreakdown: "List[UsageForType]"
    """Storage usage per type (bytes)."""


class TrackCacheStorageForOriginParameters(TypedDict):
    origin: "str"
    """Security origin."""


class UntrackCacheStorageForOriginParameters(TypedDict):
    origin: "str"
    """Security origin."""


class TrackIndexedDBForOriginParameters(TypedDict):
    origin: "str"
    """Security origin."""


class UntrackIndexedDBForOriginParameters(TypedDict):
    origin: "str"
    """Security origin."""
