# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Storage Domain Events"""

from typing_extensions import TypedDict

"""A cache has been added/deleted."""


class CacheStorageListUpdatedEvent(TypedDict):
    origin: "str"
    """Origin to update."""


"""A cache's contents have been modified."""


class CacheStorageContentUpdatedEvent(TypedDict):
    origin: "str"
    """Origin to update."""
    cacheName: "str"
    """Name of cache in origin."""


"""The origin's IndexedDB database list has been modified."""


class IndexedDBListUpdatedEvent(TypedDict):
    origin: "str"
    """Origin to update."""


"""The origin's IndexedDB object store has been modified."""


class IndexedDBContentUpdatedEvent(TypedDict):
    origin: "str"
    """Origin to update."""
    databaseName: "str"
    """Database to update."""
    objectStoreName: "str"
    """ObjectStore to update."""
