# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Storage Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import ClearDataForOriginParameters
    from .commands import GetUsageAndQuotaParameters
    from .commands import GetUsageAndQuotaReturns
    from .commands import TrackCacheStorageForOriginParameters
    from .commands import TrackIndexedDBForOriginParameters
    from .commands import UntrackCacheStorageForOriginParameters
    from .commands import UntrackIndexedDBForOriginParameters


class StorageClient:
    """Client for Storage domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def clearDataForOrigin(
        self,
        params: "ClearDataForOriginParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Clears storage for origin."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Storage.clearDataForOrigin",
                params=params,
                session_id=session_id,
            ),
        )

    async def getUsageAndQuota(
        self,
        params: "GetUsageAndQuotaParameters",
        session_id: Optional[str] = None,
    ) -> "GetUsageAndQuotaReturns":
        """Returns usage and quota in bytes."""
        return cast(
            "GetUsageAndQuotaReturns",
            await self._client.send_raw(
                method="Storage.getUsageAndQuota",
                params=params,
                session_id=session_id,
            ),
        )

    async def trackCacheStorageForOrigin(
        self,
        params: "TrackCacheStorageForOriginParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Registers origin to be notified when an update occurs to its cache storage list."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Storage.trackCacheStorageForOrigin",
                params=params,
                session_id=session_id,
            ),
        )

    async def untrackCacheStorageForOrigin(
        self,
        params: "UntrackCacheStorageForOriginParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Unregisters origin from receiving notifications for cache storage."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Storage.untrackCacheStorageForOrigin",
                params=params,
                session_id=session_id,
            ),
        )

    async def trackIndexedDBForOrigin(
        self,
        params: "TrackIndexedDBForOriginParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Registers origin to be notified when an update occurs to its IndexedDB."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Storage.trackIndexedDBForOrigin",
                params=params,
                session_id=session_id,
            ),
        )

    async def untrackIndexedDBForOrigin(
        self,
        params: "UntrackIndexedDBForOriginParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Unregisters origin from receiving notifications for IndexedDB."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Storage.untrackIndexedDBForOrigin",
                params=params,
                session_id=session_id,
            ),
        )
