# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Storage Domain Event Registration"""

from typing import Callable, Optional

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import (
        CacheStorageContentUpdatedEvent,
        CacheStorageListUpdatedEvent,
        IndexedDBContentUpdatedEvent,
        IndexedDBListUpdatedEvent,
    )


class StorageRegistration:
    """Event registration interface for Storage domain."""

    def __init__(self, registry: "EventRegistry"):
        self._registry = registry
        self._domain = "Storage"

    def cacheStorageListUpdated(
        self,
        callback: Callable[["CacheStorageListUpdatedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for cacheStorageListUpdated events.

        A cache has been added/deleted.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Storage.cacheStorageListUpdated", callback)

    def cacheStorageContentUpdated(
        self,
        callback: Callable[["CacheStorageContentUpdatedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for cacheStorageContentUpdated events.

        A cache's contents have been modified.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Storage.cacheStorageContentUpdated", callback)

    def indexedDBListUpdated(
        self,
        callback: Callable[["IndexedDBListUpdatedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for indexedDBListUpdated events.

        The origin's IndexedDB database list has been modified.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Storage.indexedDBListUpdated", callback)

    def indexedDBContentUpdated(
        self,
        callback: Callable[["IndexedDBContentUpdatedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for indexedDBContentUpdated events.

        The origin's IndexedDB object store has been modified.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Storage.indexedDBContentUpdated", callback)
