# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Storage Domain Types"""

from typing_extensions import Literal
from typing_extensions import TypedDict

StorageType = Literal[
    "appcache",
    "cookies",
    "file_systems",
    "indexeddb",
    "local_storage",
    "shader_cache",
    "websql",
    "service_workers",
    "cache_storage",
    "all",
    "other",
]
"""Enum of possible storage types."""


class UsageForType(TypedDict):
    """Usage for a storage type."""

    storageType: "StorageType"
    """Name of storage type."""
    usage: "float"
    """Storage usage (bytes)."""
