# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP HeadlessExperimental Domain Commands"""

from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..runtime.types import Timestamp
    from .types import ScreenshotParams


class BeginFrameParameters(TypedDict, total=False):
    frameTime: "Timestamp"
    """Timestamp of this BeginFrame (milliseconds since epoch). If not set, the current time will be used."""
    deadline: "Timestamp"
    """Deadline of this BeginFrame (milliseconds since epoch). If not set, the deadline will be calculated from the frameTime and interval."""
    interval: "float"
    """The interval between BeginFrames that is reported to the compositor, in milliseconds. Defaults to a 60 frames/second interval, i.e. about 16.666 milliseconds."""
    screenshot: "ScreenshotParams"
    """If set, a screenshot of the frame will be captured and returned in the response. Otherwise, no screenshot will be captured."""


class BeginFrameReturns(TypedDict):
    hasDamage: "bool"
    """Whether the BeginFrame resulted in damage and, thus, a new frame was committed to the display."""
    mainFrameContentUpdated: "bool"
    """Whether the main frame submitted a new display frame in response to this BeginFrame."""
    screenshotData: "str"
    """Base64-encoded image data of the screenshot, if one was requested and successfully taken."""
