# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP HeadlessExperimental Domain Events"""

from typing_extensions import TypedDict

"""Issued when the target starts or stops needing BeginFrames."""


class NeedsBeginFramesChangedEvent(TypedDict):
    needsBeginFrames: "bool"
    """True if BeginFrames are needed, false otherwise."""


"""Issued when the main frame has first submitted a frame to the browser. May only be fired while a BeginFrame is in flight. Before this event, screenshotting requests may fail."""


class MainFrameReadyForScreenshotsEvent(TypedDict):
    pass
