# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Network Domain Commands"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..debugger.types import SearchMatch
    from .types import AuthChallengeResponse
    from .types import ConnectionType
    from .types import Cookie
    from .types import CookieParam
    from .types import CookieSameSite
    from .types import ErrorReason
    from .types import Headers
    from .types import InterceptionId
    from .types import RequestId
    from .types import RequestPattern
    from .types import TimeSinceEpoch


class EnableParameters(TypedDict, total=False):
    maxTotalBufferSize: "int"
    """Buffer size in bytes to use when preserving network payloads (XHRs, etc)."""
    maxResourceBufferSize: "int"
    """Per-resource buffer size in bytes to use when preserving network payloads (XHRs, etc)."""


class SetUserAgentOverrideParameters(TypedDict):
    userAgent: "str"
    """User agent to use."""


class SearchInResponseBodyParameters(TypedDict):
    requestId: "RequestId"
    """Identifier of the network response to search."""
    query: "str"
    """String to search for."""
    caseSensitive: "NotRequired[bool]"
    """If true, search is case sensitive."""
    isRegex: "NotRequired[bool]"
    """If true, treats string parameter as regex."""


class SearchInResponseBodyReturns(TypedDict):
    result: "List[SearchMatch]"
    """List of search matches."""


class SetExtraHTTPHeadersParameters(TypedDict):
    headers: "Headers"
    """Map with extra HTTP headers."""


class GetResponseBodyParameters(TypedDict):
    requestId: "RequestId"
    """Identifier of the network request to get content for."""


class GetResponseBodyReturns(TypedDict):
    body: "str"
    """Response body."""
    base64Encoded: "bool"
    """True, if content was sent as base64."""


class SetBlockedURLsParameters(TypedDict):
    urls: "List[str]"
    """URL patterns to block. Wildcards ('*') are allowed."""


class ReplayXHRParameters(TypedDict):
    requestId: "RequestId"
    """Identifier of XHR to replay."""


class CanClearBrowserCacheReturns(TypedDict):
    result: "bool"
    """True if browser cache can be cleared."""


class CanClearBrowserCookiesReturns(TypedDict):
    result: "bool"
    """True if browser cookies can be cleared."""


class GetCookiesParameters(TypedDict, total=False):
    urls: "List[str]"
    """The list of URLs for which applicable cookies will be fetched"""


class GetCookiesReturns(TypedDict):
    cookies: "List[Cookie]"
    """Array of cookie objects."""


class GetAllCookiesReturns(TypedDict):
    cookies: "List[Cookie]"
    """Array of cookie objects."""


class DeleteCookiesParameters(TypedDict):
    name: "str"
    """Name of the cookies to remove."""
    url: "NotRequired[str]"
    """If specified, deletes all the cookies with the given name where domain and path match provided URL."""
    domain: "NotRequired[str]"
    """If specified, deletes only cookies with the exact domain."""
    path: "NotRequired[str]"
    """If specified, deletes only cookies with the exact path."""


class SetCookieParameters(TypedDict):
    name: "str"
    """Cookie name."""
    value: "str"
    """Cookie value."""
    url: "NotRequired[str]"
    """The request-URI to associate with the setting of the cookie. This value can affect the default domain and path values of the created cookie."""
    domain: "NotRequired[str]"
    """Cookie domain."""
    path: "NotRequired[str]"
    """Cookie path."""
    secure: "NotRequired[bool]"
    """True if cookie is secure."""
    httpOnly: "NotRequired[bool]"
    """True if cookie is http-only."""
    sameSite: "NotRequired[CookieSameSite]"
    """Cookie SameSite type."""
    expires: "NotRequired[TimeSinceEpoch]"
    """Cookie expiration date, session cookie if not set"""


class SetCookieReturns(TypedDict):
    success: "bool"
    """True if successfully set cookie."""


class SetCookiesParameters(TypedDict):
    cookies: "List[CookieParam]"
    """Cookies to be set."""


class CanEmulateNetworkConditionsReturns(TypedDict):
    result: "bool"
    """True if emulation of network conditions is supported."""


class EmulateNetworkConditionsParameters(TypedDict):
    offline: "bool"
    """True to emulate internet disconnection."""
    latency: "float"
    """Minimum latency from request sent to response headers received (ms)."""
    downloadThroughput: "float"
    """Maximal aggregated download throughput (bytes/sec). -1 disables download throttling."""
    uploadThroughput: "float"
    """Maximal aggregated upload throughput (bytes/sec).  -1 disables upload throttling."""
    connectionType: "NotRequired[ConnectionType]"
    """Connection type if known."""


class SetCacheDisabledParameters(TypedDict):
    cacheDisabled: "bool"
    """Cache disabled state."""


class SetBypassServiceWorkerParameters(TypedDict):
    bypass: "bool"
    """Bypass service worker and load from network."""


class SetDataSizeLimitsForTestParameters(TypedDict):
    maxTotalSize: "int"
    """Maximum total buffer size."""
    maxResourceSize: "int"
    """Maximum per-resource size."""


class GetCertificateParameters(TypedDict):
    origin: "str"
    """Origin to get certificate for."""


class GetCertificateReturns(TypedDict):
    tableNames: "List[str]"


class SetRequestInterceptionParameters(TypedDict):
    patterns: "List[RequestPattern]"
    """Requests matching any of these patterns will be forwarded and wait for the corresponding continueInterceptedRequest call."""


class ContinueInterceptedRequestParameters(TypedDict):
    interceptionId: "InterceptionId"
    errorReason: "NotRequired[ErrorReason]"
    """If set this causes the request to fail with the given reason. Passing <code>Aborted</code> for requests marked with <code>isNavigationRequest</code> also cancels the navigation. Must not be set in response to an authChallenge."""
    rawResponse: "NotRequired[str]"
    """If set the requests completes using with the provided base64 encoded raw response, including HTTP status line and headers etc... Must not be set in response to an authChallenge."""
    url: "NotRequired[str]"
    """If set the request url will be modified in a way that's not observable by page. Must not be set in response to an authChallenge."""
    method: "NotRequired[str]"
    """If set this allows the request method to be overridden. Must not be set in response to an authChallenge."""
    postData: "NotRequired[str]"
    """If set this allows postData to be set. Must not be set in response to an authChallenge."""
    headers: "NotRequired[Headers]"
    """If set this allows the request headers to be changed. Must not be set in response to an authChallenge."""
    authChallengeResponse: "NotRequired[AuthChallengeResponse]"
    """Response to a requestIntercepted with an authChallenge. Must not be set otherwise."""


class GetResponseBodyForInterceptionParameters(TypedDict):
    interceptionId: "InterceptionId"
    """Identifier for the intercepted request to get body for."""


class GetResponseBodyForInterceptionReturns(TypedDict):
    body: "str"
    """Response body."""
    base64Encoded: "bool"
    """True, if content was sent as base64."""
