# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Network Domain Events"""

from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..page.types import FrameId
    from ..page.types import ResourceType
    from .types import AuthChallenge
    from .types import BlockedReason
    from .types import ErrorReason
    from .types import Headers
    from .types import Initiator
    from .types import InterceptionId
    from .types import LoaderId
    from .types import MonotonicTime
    from .types import Request
    from .types import RequestId
    from .types import ResourcePriority
    from .types import Response
    from .types import TimeSinceEpoch
    from .types import WebSocketFrame
    from .types import WebSocketRequest
    from .types import WebSocketResponse

"""Fired when resource loading priority is changed"""


class ResourceChangedPriorityEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    newPriority: "ResourcePriority"
    """New priority"""
    timestamp: "MonotonicTime"
    """Timestamp."""


"""Fired when page is about to send HTTP request."""


class RequestWillBeSentEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    loaderId: "LoaderId"
    """Loader identifier. Empty string if the request is fetched from worker."""
    documentURL: "str"
    """URL of the document this request is loaded for."""
    request: "Request"
    """Request data."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    wallTime: "TimeSinceEpoch"
    """Timestamp."""
    initiator: "Initiator"
    """Request initiator."""
    redirectResponse: "NotRequired[Response]"
    """Redirect response data."""
    type: "NotRequired[ResourceType]"
    """Type of this resource."""
    frameId: "NotRequired[FrameId]"
    """Frame identifier."""


"""Fired if request ended up loading from cache."""


class RequestServedFromCacheEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""


"""Fired when HTTP response is available."""


class ResponseReceivedEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    loaderId: "LoaderId"
    """Loader identifier. Empty string if the request is fetched from worker."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    type: "ResourceType"
    """Resource type."""
    response: "Response"
    """Response data."""
    frameId: "NotRequired[FrameId]"
    """Frame identifier."""


"""Fired when data chunk was received over the network."""


class DataReceivedEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    dataLength: "int"
    """Data chunk length."""
    encodedDataLength: "int"
    """Actual bytes received (might be less than dataLength for compressed encodings)."""


"""Fired when HTTP request has finished loading."""


class LoadingFinishedEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    encodedDataLength: "float"
    """Total number of bytes received for this request."""


"""Fired when HTTP request has failed to load."""


class LoadingFailedEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    type: "ResourceType"
    """Resource type."""
    errorText: "str"
    """User friendly error message."""
    canceled: "NotRequired[bool]"
    """True if loading was canceled."""
    blockedReason: "NotRequired[BlockedReason]"
    """The reason why loading was blocked, if any."""


"""Fired when WebSocket is about to initiate handshake."""


class WebSocketWillSendHandshakeRequestEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    wallTime: "TimeSinceEpoch"
    """UTC Timestamp."""
    request: "WebSocketRequest"
    """WebSocket request data."""


"""Fired when WebSocket handshake response becomes available."""


class WebSocketHandshakeResponseReceivedEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    response: "WebSocketResponse"
    """WebSocket response data."""


"""Fired upon WebSocket creation."""


class WebSocketCreatedEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    url: "str"
    """WebSocket request URL."""
    initiator: "NotRequired[Initiator]"
    """Request initiator."""


"""Fired when WebSocket is closed."""


class WebSocketClosedEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""


"""Fired when WebSocket frame is received."""


class WebSocketFrameReceivedEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    response: "WebSocketFrame"
    """WebSocket response data."""


"""Fired when WebSocket frame error occurs."""


class WebSocketFrameErrorEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    errorMessage: "str"
    """WebSocket frame error message."""


"""Fired when WebSocket frame is sent."""


class WebSocketFrameSentEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    response: "WebSocketFrame"
    """WebSocket response data."""


"""Fired when EventSource message is received."""


class EventSourceMessageReceivedEvent(TypedDict):
    requestId: "RequestId"
    """Request identifier."""
    timestamp: "MonotonicTime"
    """Timestamp."""
    eventName: "str"
    """Message type."""
    eventId: "str"
    """Message identifier."""
    data: "str"
    """Message content."""


"""Details of an intercepted HTTP request, which must be either allowed, blocked, modified or mocked."""


class RequestInterceptedEvent(TypedDict):
    interceptionId: "InterceptionId"
    """Each request the page makes will have a unique id, however if any redirects are encountered while processing that fetch, they will be reported with the same id as the original fetch. Likewise if HTTP authentication is needed then the same fetch id will be used."""
    request: "Request"
    frameId: "FrameId"
    """The id of the frame that initiated the request."""
    resourceType: "ResourceType"
    """How the requested resource will be used."""
    isNavigationRequest: "bool"
    """Whether this is a navigation request, which can abort the navigation completely."""
    redirectUrl: "NotRequired[str]"
    """Redirect location, only sent if a redirect was intercepted."""
    authChallenge: "NotRequired[AuthChallenge]"
    """Details of the Authorization Challenge encountered. If this is set then continueInterceptedRequest must contain an authChallengeResponse."""
    responseErrorReason: "NotRequired[ErrorReason]"
    """Response error if intercepted at response stage or if redirect occurred while intercepting request."""
    responseStatusCode: "NotRequired[int]"
    """Response code if intercepted at response stage or if redirect occurred while intercepting request or auth retry occurred."""
    responseHeaders: "NotRequired[Headers]"
    """Response headers if intercepted at the response stage or if redirect occurred while intercepting request or auth retry occurred."""
