# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Network Domain Event Registration"""

from typing import Callable, Optional

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import (
        DataReceivedEvent,
        EventSourceMessageReceivedEvent,
        LoadingFailedEvent,
        LoadingFinishedEvent,
        RequestInterceptedEvent,
        RequestServedFromCacheEvent,
        RequestWillBeSentEvent,
        ResourceChangedPriorityEvent,
        ResponseReceivedEvent,
        WebSocketClosedEvent,
        WebSocketCreatedEvent,
        WebSocketFrameErrorEvent,
        WebSocketFrameReceivedEvent,
        WebSocketFrameSentEvent,
        WebSocketHandshakeResponseReceivedEvent,
        WebSocketWillSendHandshakeRequestEvent,
    )


class NetworkRegistration:
    """Event registration interface for Network domain."""

    def __init__(self, registry: "EventRegistry"):
        self._registry = registry
        self._domain = "Network"

    def resourceChangedPriority(
        self,
        callback: Callable[["ResourceChangedPriorityEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for resourceChangedPriority events.

        Fired when resource loading priority is changed

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.resourceChangedPriority", callback)

    def requestWillBeSent(
        self,
        callback: Callable[["RequestWillBeSentEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for requestWillBeSent events.

        Fired when page is about to send HTTP request.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.requestWillBeSent", callback)

    def requestServedFromCache(
        self,
        callback: Callable[["RequestServedFromCacheEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for requestServedFromCache events.

        Fired if request ended up loading from cache.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.requestServedFromCache", callback)

    def responseReceived(
        self,
        callback: Callable[["ResponseReceivedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for responseReceived events.

        Fired when HTTP response is available.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.responseReceived", callback)

    def dataReceived(
        self,
        callback: Callable[["DataReceivedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for dataReceived events.

        Fired when data chunk was received over the network.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.dataReceived", callback)

    def loadingFinished(
        self,
        callback: Callable[["LoadingFinishedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for loadingFinished events.

        Fired when HTTP request has finished loading.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.loadingFinished", callback)

    def loadingFailed(
        self,
        callback: Callable[["LoadingFailedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for loadingFailed events.

        Fired when HTTP request has failed to load.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.loadingFailed", callback)

    def webSocketWillSendHandshakeRequest(
        self,
        callback: Callable[
            ["WebSocketWillSendHandshakeRequestEvent", Optional[str]], None
        ],
    ) -> None:
        """
        Register a callback for webSocketWillSendHandshakeRequest events.

        Fired when WebSocket is about to initiate handshake.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.webSocketWillSendHandshakeRequest", callback)

    def webSocketHandshakeResponseReceived(
        self,
        callback: Callable[
            ["WebSocketHandshakeResponseReceivedEvent", Optional[str]], None
        ],
    ) -> None:
        """
        Register a callback for webSocketHandshakeResponseReceived events.

        Fired when WebSocket handshake response becomes available.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.webSocketHandshakeResponseReceived", callback)

    def webSocketCreated(
        self,
        callback: Callable[["WebSocketCreatedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for webSocketCreated events.

        Fired upon WebSocket creation.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.webSocketCreated", callback)

    def webSocketClosed(
        self,
        callback: Callable[["WebSocketClosedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for webSocketClosed events.

        Fired when WebSocket is closed.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.webSocketClosed", callback)

    def webSocketFrameReceived(
        self,
        callback: Callable[["WebSocketFrameReceivedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for webSocketFrameReceived events.

        Fired when WebSocket frame is received.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.webSocketFrameReceived", callback)

    def webSocketFrameError(
        self,
        callback: Callable[["WebSocketFrameErrorEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for webSocketFrameError events.

        Fired when WebSocket frame error occurs.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.webSocketFrameError", callback)

    def webSocketFrameSent(
        self,
        callback: Callable[["WebSocketFrameSentEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for webSocketFrameSent events.

        Fired when WebSocket frame is sent.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.webSocketFrameSent", callback)

    def eventSourceMessageReceived(
        self,
        callback: Callable[["EventSourceMessageReceivedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for eventSourceMessageReceived events.

        Fired when EventSource message is received.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.eventSourceMessageReceived", callback)

    def requestIntercepted(
        self,
        callback: Callable[["RequestInterceptedEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for requestIntercepted events.

        Details of an intercepted HTTP request, which must be either allowed, blocked, modified or mocked.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Network.requestIntercepted", callback)
