# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Network Domain Types"""

from typing import List
from typing_extensions import Literal
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..page.types import ResourceType
    from ..runtime.types import StackTrace
    from ..security.types import CertificateId
    from ..security.types import MixedContentType
    from ..security.types import SecurityState

LoaderId = str
"""Unique loader identifier."""


RequestId = str
"""Unique request identifier."""


InterceptionId = str
"""Unique intercepted request identifier."""


ErrorReason = Literal[
    "Failed",
    "Aborted",
    "TimedOut",
    "AccessDenied",
    "ConnectionClosed",
    "ConnectionReset",
    "ConnectionRefused",
    "ConnectionAborted",
    "ConnectionFailed",
    "NameNotResolved",
    "InternetDisconnected",
    "AddressUnreachable",
]
"""Network level fetch failure reason."""


TimeSinceEpoch = float
"""UTC time in seconds, counted from January 1, 1970."""


MonotonicTime = float
"""Monotonically increasing time in seconds since an arbitrary point in the past."""


class Headers(TypedDict):
    """Request / response headers as keys / values of JSON object."""


ConnectionType = Literal[
    "none",
    "cellular2g",
    "cellular3g",
    "cellular4g",
    "bluetooth",
    "ethernet",
    "wifi",
    "wimax",
    "other",
]
"""The underlying connection technology that the browser is supposedly using."""


CookieSameSite = Literal["Strict", "Lax"]
"""Represents the cookie's 'SameSite' status: https://tools.ietf.org/html/draft-west-first-party-cookies"""


class ResourceTiming(TypedDict):
    """Timing information for the request."""

    requestTime: "float"
    """Timing's requestTime is a baseline in seconds, while the other numbers are ticks in milliseconds relatively to this requestTime."""
    proxyStart: "float"
    """Started resolving proxy."""
    proxyEnd: "float"
    """Finished resolving proxy."""
    dnsStart: "float"
    """Started DNS address resolve."""
    dnsEnd: "float"
    """Finished DNS address resolve."""
    connectStart: "float"
    """Started connecting to the remote host."""
    connectEnd: "float"
    """Connected to the remote host."""
    sslStart: "float"
    """Started SSL handshake."""
    sslEnd: "float"
    """Finished SSL handshake."""
    workerStart: "float"
    """Started running ServiceWorker."""
    workerReady: "float"
    """Finished Starting ServiceWorker."""
    sendStart: "float"
    """Started sending request."""
    sendEnd: "float"
    """Finished sending request."""
    pushStart: "float"
    """Time the server started pushing request."""
    pushEnd: "float"
    """Time the server finished pushing request."""
    receiveHeadersEnd: "float"
    """Finished receiving response headers."""


ResourcePriority = Literal["VeryLow", "Low", "Medium", "High", "VeryHigh"]
"""Loading priority of a resource request."""


class Request(TypedDict):
    """HTTP request data."""

    url: "str"
    """Request URL."""
    method: "str"
    """HTTP request method."""
    headers: "Headers"
    """HTTP request headers."""
    postData: "NotRequired[str]"
    """HTTP POST request data."""
    mixedContentType: "NotRequired[MixedContentType]"
    """The mixed content type of the request."""
    initialPriority: "ResourcePriority"
    """Priority of the resource request at the time request is sent."""
    referrerPolicy: "str"
    """The referrer policy of the request, as defined in https://www.w3.org/TR/referrer-policy/"""
    isLinkPreload: "NotRequired[bool]"
    """Whether is loaded via link preload."""


class SignedCertificateTimestamp(TypedDict):
    """Details of a signed certificate timestamp (SCT)."""

    status: "str"
    """Validation status."""
    origin: "str"
    """Origin."""
    logDescription: "str"
    """Log name / description."""
    logId: "str"
    """Log ID."""
    timestamp: "TimeSinceEpoch"
    """Issuance date."""
    hashAlgorithm: "str"
    """Hash algorithm."""
    signatureAlgorithm: "str"
    """Signature algorithm."""
    signatureData: "str"
    """Signature data."""


class SecurityDetails(TypedDict):
    """Security details about a request."""

    protocol: "str"
    """Protocol name (e.g. \"TLS 1.2\" or \"QUIC\")."""
    keyExchange: "str"
    """Key Exchange used by the connection, or the empty string if not applicable."""
    keyExchangeGroup: "NotRequired[str]"
    """(EC)DH group used by the connection, if applicable."""
    cipher: "str"
    """Cipher name."""
    mac: "NotRequired[str]"
    """TLS MAC. Note that AEAD ciphers do not have separate MACs."""
    certificateId: "CertificateId"
    """Certificate ID value."""
    subjectName: "str"
    """Certificate subject name."""
    sanList: "List[str]"
    """Subject Alternative Name (SAN) DNS names and IP addresses."""
    issuer: "str"
    """Name of the issuing CA."""
    validFrom: "TimeSinceEpoch"
    """Certificate valid from date."""
    validTo: "TimeSinceEpoch"
    """Certificate valid to (expiration) date"""
    signedCertificateTimestampList: "List[SignedCertificateTimestamp]"
    """List of signed certificate timestamps (SCTs)."""


BlockedReason = Literal[
    "csp", "mixed-content", "origin", "inspector", "subresource-filter", "other"
]
"""The reason why request was blocked."""


class Response(TypedDict):
    """HTTP response data."""

    url: "str"
    """Response URL. This URL can be different from CachedResource.url in case of redirect."""
    status: "int"
    """HTTP response status code."""
    statusText: "str"
    """HTTP response status text."""
    headers: "Headers"
    """HTTP response headers."""
    headersText: "NotRequired[str]"
    """HTTP response headers text."""
    mimeType: "str"
    """Resource mimeType as determined by the browser."""
    requestHeaders: "NotRequired[Headers]"
    """Refined HTTP request headers that were actually transmitted over the network."""
    requestHeadersText: "NotRequired[str]"
    """HTTP request headers text."""
    connectionReused: "bool"
    """Specifies whether physical connection was actually reused for this request."""
    connectionId: "float"
    """Physical connection id that was actually used for this request."""
    remoteIPAddress: "NotRequired[str]"
    """Remote IP address."""
    remotePort: "NotRequired[int]"
    """Remote port."""
    fromDiskCache: "NotRequired[bool]"
    """Specifies that the request was served from the disk cache."""
    fromServiceWorker: "NotRequired[bool]"
    """Specifies that the request was served from the ServiceWorker."""
    encodedDataLength: "float"
    """Total number of bytes received for this request so far."""
    timing: "NotRequired[ResourceTiming]"
    """Timing information for the given request."""
    protocol: "NotRequired[str]"
    """Protocol used to fetch this request."""
    securityState: "SecurityState"
    """Security state of the request resource."""
    securityDetails: "NotRequired[SecurityDetails]"
    """Security details for the request."""


class WebSocketRequest(TypedDict):
    """WebSocket request data."""

    headers: "Headers"
    """HTTP request headers."""


class WebSocketResponse(TypedDict):
    """WebSocket response data."""

    status: "int"
    """HTTP response status code."""
    statusText: "str"
    """HTTP response status text."""
    headers: "Headers"
    """HTTP response headers."""
    headersText: "NotRequired[str]"
    """HTTP response headers text."""
    requestHeaders: "NotRequired[Headers]"
    """HTTP request headers."""
    requestHeadersText: "NotRequired[str]"
    """HTTP request headers text."""


class WebSocketFrame(TypedDict):
    """WebSocket frame data."""

    opcode: "float"
    """WebSocket frame opcode."""
    mask: "bool"
    """WebSocke frame mask."""
    payloadData: "str"
    """WebSocke frame payload data."""


class CachedResource(TypedDict):
    """Information about the cached resource."""

    url: "str"
    """Resource URL. This is the url of the original network request."""
    type: "ResourceType"
    """Type of this resource."""
    response: "NotRequired[Response]"
    """Cached response data."""
    bodySize: "float"
    """Cached response body size."""


class Initiator(TypedDict):
    """Information about the request initiator."""

    type: "str"
    """Type of this initiator."""
    stack: "NotRequired[StackTrace]"
    """Initiator JavaScript stack trace, set for Script only."""
    url: "NotRequired[str]"
    """Initiator URL, set for Parser type or for Script type (when script is importing module)."""
    lineNumber: "NotRequired[float]"
    """Initiator line number, set for Parser type or for Script type (when script is importing module) (0-based)."""


class Cookie(TypedDict):
    """Cookie object"""

    name: "str"
    """Cookie name."""
    value: "str"
    """Cookie value."""
    domain: "str"
    """Cookie domain."""
    path: "str"
    """Cookie path."""
    expires: "float"
    """Cookie expiration date as the number of seconds since the UNIX epoch."""
    size: "int"
    """Cookie size."""
    httpOnly: "bool"
    """True if cookie is http-only."""
    secure: "bool"
    """True if cookie is secure."""
    session: "bool"
    """True in case of session cookie."""
    sameSite: "NotRequired[CookieSameSite]"
    """Cookie SameSite type."""


class CookieParam(TypedDict):
    """Cookie parameter object"""

    name: "str"
    """Cookie name."""
    value: "str"
    """Cookie value."""
    url: "NotRequired[str]"
    """The request-URI to associate with the setting of the cookie. This value can affect the default domain and path values of the created cookie."""
    domain: "NotRequired[str]"
    """Cookie domain."""
    path: "NotRequired[str]"
    """Cookie path."""
    secure: "NotRequired[bool]"
    """True if cookie is secure."""
    httpOnly: "NotRequired[bool]"
    """True if cookie is http-only."""
    sameSite: "NotRequired[CookieSameSite]"
    """Cookie SameSite type."""
    expires: "NotRequired[TimeSinceEpoch]"
    """Cookie expiration date, session cookie if not set"""


class AuthChallenge(TypedDict):
    """Authorization challenge for HTTP status code 401 or 407."""

    source: "NotRequired[str]"
    """Source of the authentication challenge."""
    origin: "str"
    """Origin of the challenger."""
    scheme: "str"
    """The authentication scheme used, such as basic or digest"""
    realm: "str"
    """The realm of the challenge. May be empty."""


class AuthChallengeResponse(TypedDict):
    """Response to an AuthChallenge."""

    response: "str"
    """The decision on what to do in response to the authorization challenge.  Default means deferring to the default behavior of the net stack, which will likely either the Cancel authentication or display a popup dialog box."""
    username: "NotRequired[str]"
    """The username to provide, possibly empty. Should only be set if response is ProvideCredentials."""
    password: "NotRequired[str]"
    """The password to provide, possibly empty. Should only be set if response is ProvideCredentials."""


InterceptionStage = Literal["Request", "HeadersReceived"]
"""Stages of the interception to begin intercepting. Request will intercept before the request is sent. Response will intercept after the response is received."""


class RequestPattern(TypedDict, total=False):
    """Request pattern for interception."""

    urlPattern: "str"
    """Wildcards ('*' -> zero or more, '?' -> exactly one) are allowed. Escape character is backslash. Omitting is equivalent to \"*\"."""
    resourceType: "ResourceType"
    """If set, only requests for matching resource types will be intercepted."""
    interceptionStage: "InterceptionStage"
    """Stage at wich to begin intercepting requests. Default is Request."""
