# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP SystemInfo Domain Commands"""

from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import GPUInfo


class GetInfoReturns(TypedDict):
    gpu: "GPUInfo"
    """Information about the GPUs on the system."""
    modelName: "str"
    """A platform-dependent description of the model of the machine. On Mac OS, this is, for example, 'MacBookPro'. Will be the empty string if not supported."""
    modelVersion: "str"
    """A platform-dependent description of the version of the machine. On Mac OS, this is, for example, '10.1'. Will be the empty string if not supported."""
    commandLine: "str"
    """The command line string used to launch the browser. Will be the empty string if not supported."""
