# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP SystemInfo Domain Types"""

from typing import Any, Dict, List
from typing_extensions import NotRequired, TypedDict


class GPUDevice(TypedDict):
    """Describes a single graphics processor (GPU)."""

    vendorId: "float"
    """PCI ID of the GPU vendor, if available; 0 otherwise."""
    deviceId: "float"
    """PCI ID of the GPU device, if available; 0 otherwise."""
    vendorString: "str"
    """String description of the GPU vendor, if the PCI ID is not available."""
    deviceString: "str"
    """String description of the GPU device, if the PCI ID is not available."""


class GPUInfo(TypedDict):
    """Provides information about the GPU(s) on the system."""

    devices: "List[GPUDevice]"
    """The graphics devices on the system. Element 0 is the primary GPU."""
    auxAttributes: "NotRequired[Dict[str, Any]]"
    """An optional dictionary of additional GPU related attributes."""
    featureStatus: "NotRequired[Dict[str, Any]]"
    """An optional dictionary of graphics features and their status."""
    driverBugWorkarounds: "List[str]"
    """An optional array of GPU driver bug workarounds."""
