# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DOM Domain Commands"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import BackendNodeId
    from ..runtime.types import RemoteObject
    from ..runtime.types import RemoteObjectId
    from .types import BackendNodeId
    from .types import BoxModel
    from .types import Node
    from .types import NodeId


class GetDocumentParameters(TypedDict, total=False):
    depth: "int"
    """The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the entire subtree or provide an integer larger than 0."""
    pierce: "bool"
    """Whether or not iframes and shadow roots should be traversed when returning the subtree (default is false)."""


class GetDocumentReturns(TypedDict):
    root: "Node"
    """Resulting node."""


class GetFlattenedDocumentParameters(TypedDict, total=False):
    depth: "int"
    """The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the entire subtree or provide an integer larger than 0."""
    pierce: "bool"
    """Whether or not iframes and shadow roots should be traversed when returning the subtree (default is false)."""


class GetFlattenedDocumentReturns(TypedDict):
    nodes: "List[Node]"
    """Resulting node."""


class CollectClassNamesFromSubtreeParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to collect class names."""


class CollectClassNamesFromSubtreeReturns(TypedDict):
    classNames: "List[str]"
    """Class name list."""


class RequestChildNodesParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to get children for."""
    depth: "NotRequired[int]"
    """The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the entire subtree or provide an integer larger than 0."""
    pierce: "NotRequired[bool]"
    """Whether or not iframes and shadow roots should be traversed when returning the sub-tree (default is false)."""


class QuerySelectorParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to query upon."""
    selector: "str"
    """Selector string."""


class QuerySelectorReturns(TypedDict):
    nodeId: "NodeId"
    """Query selector result."""


class QuerySelectorAllParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to query upon."""
    selector: "str"
    """Selector string."""


class QuerySelectorAllReturns(TypedDict):
    nodeIds: "List[NodeId]"
    """Query selector result."""


class SetNodeNameParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to set name for."""
    name: "str"
    """New node's name."""


class SetNodeNameReturns(TypedDict):
    nodeId: "NodeId"
    """New node's id."""


class SetNodeValueParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to set value for."""
    value: "str"
    """New node's value."""


class RemoveNodeParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to remove."""


class SetAttributeValueParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the element to set attribute for."""
    name: "str"
    """Attribute name."""
    value: "str"
    """Attribute value."""


class SetAttributesAsTextParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the element to set attributes for."""
    text: "str"
    """Text with a number of attributes. Will parse this text using HTML parser."""
    name: "NotRequired[str]"
    """Attribute name to replace with new attributes derived from text in case text parsed successfully."""


class RemoveAttributeParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the element to remove attribute from."""
    name: "str"
    """Name of the attribute to remove."""


class GetOuterHTMLParameters(TypedDict, total=False):
    nodeId: "NodeId"
    """Identifier of the node."""
    backendNodeId: "BackendNodeId"
    """Identifier of the backend node."""
    objectId: "RemoteObjectId"
    """JavaScript object id of the node wrapper."""


class GetOuterHTMLReturns(TypedDict):
    outerHTML: "str"
    """Outer HTML markup."""


class SetOuterHTMLParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to set markup for."""
    outerHTML: "str"
    """Outer HTML markup to set."""


class PerformSearchParameters(TypedDict):
    query: "str"
    """Plain text or query selector or XPath search query."""
    includeUserAgentShadowDOM: "NotRequired[bool]"
    """True to search in user agent shadow DOM."""


class PerformSearchReturns(TypedDict):
    searchId: "str"
    """Unique search session identifier."""
    resultCount: "int"
    """Number of search results."""


class GetSearchResultsParameters(TypedDict):
    searchId: "str"
    """Unique search session identifier."""
    fromIndex: "int"
    """Start index of the search result to be returned."""
    toIndex: "int"
    """End index of the search result to be returned."""


class GetSearchResultsReturns(TypedDict):
    nodeIds: "List[NodeId]"
    """Ids of the search result nodes."""


class DiscardSearchResultsParameters(TypedDict):
    searchId: "str"
    """Unique search session identifier."""


class RequestNodeParameters(TypedDict):
    objectId: "RemoteObjectId"
    """JavaScript object id to convert into node."""


class RequestNodeReturns(TypedDict):
    nodeId: "NodeId"
    """Node id for given object."""


class PushNodeByPathToFrontendParameters(TypedDict):
    path: "str"
    """Path to node in the proprietary format."""


class PushNodeByPathToFrontendReturns(TypedDict):
    nodeId: "NodeId"
    """Id of the node for given path."""


class PushNodesByBackendIdsToFrontendParameters(TypedDict):
    backendNodeIds: "List[BackendNodeId]"
    """The array of backend node ids."""


class PushNodesByBackendIdsToFrontendReturns(TypedDict):
    nodeIds: "List[NodeId]"
    """The array of ids of pushed nodes that correspond to the backend ids specified in backendNodeIds."""


class SetInspectedNodeParameters(TypedDict):
    nodeId: "NodeId"
    """DOM node id to be accessible by means of $x command line API."""


class ResolveNodeParameters(TypedDict, total=False):
    nodeId: "NodeId"
    """Id of the node to resolve."""
    backendNodeId: "BackendNodeId"
    """Backend identifier of the node to resolve."""
    objectGroup: "str"
    """Symbolic group name that can be used to release multiple objects."""


class ResolveNodeReturns(TypedDict):
    object: "RemoteObject"
    """JavaScript object wrapper for given node."""


class GetAttributesParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to retrieve attibutes for."""


class GetAttributesReturns(TypedDict):
    attributes: "List[str]"
    """An interleaved array of node attribute names and values."""


class CopyToParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to copy."""
    targetNodeId: "NodeId"
    """Id of the element to drop the copy into."""
    insertBeforeNodeId: "NotRequired[NodeId]"
    """Drop the copy before this node (if absent, the copy becomes the last child of <code>targetNodeId</code>)."""


class CopyToReturns(TypedDict):
    nodeId: "NodeId"
    """Id of the node clone."""


class MoveToParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to move."""
    targetNodeId: "NodeId"
    """Id of the element to drop the moved node into."""
    insertBeforeNodeId: "NotRequired[NodeId]"
    """Drop node before this one (if absent, the moved node becomes the last child of <code>targetNodeId</code>)."""


class MoveToReturns(TypedDict):
    nodeId: "NodeId"
    """New id of the moved node."""


class FocusParameters(TypedDict, total=False):
    nodeId: "NodeId"
    """Identifier of the node."""
    backendNodeId: "BackendNodeId"
    """Identifier of the backend node."""
    objectId: "RemoteObjectId"
    """JavaScript object id of the node wrapper."""


class SetFileInputFilesParameters(TypedDict):
    files: "List[str]"
    """Array of file paths to set."""
    nodeId: "NotRequired[NodeId]"
    """Identifier of the node."""
    backendNodeId: "NotRequired[BackendNodeId]"
    """Identifier of the backend node."""
    objectId: "NotRequired[RemoteObjectId]"
    """JavaScript object id of the node wrapper."""


class GetBoxModelParameters(TypedDict, total=False):
    nodeId: "NodeId"
    """Identifier of the node."""
    backendNodeId: "BackendNodeId"
    """Identifier of the backend node."""
    objectId: "RemoteObjectId"
    """JavaScript object id of the node wrapper."""


class GetBoxModelReturns(TypedDict):
    model: "BoxModel"
    """Box model for the node."""


class GetNodeForLocationParameters(TypedDict):
    x: "int"
    """X coordinate."""
    y: "int"
    """Y coordinate."""
    includeUserAgentShadowDOM: "NotRequired[bool]"
    """False to skip to the nearest non-UA shadow root ancestor (default: false)."""


class GetNodeForLocationReturns(TypedDict):
    nodeId: "NodeId"
    """Id of the node at given coordinates."""


class GetRelayoutBoundaryParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node."""


class GetRelayoutBoundaryReturns(TypedDict):
    nodeId: "NodeId"
    """Relayout boundary node id for the given node."""


class DescribeNodeParameters(TypedDict, total=False):
    nodeId: "NodeId"
    """Identifier of the node."""
    backendNodeId: "BackendNodeId"
    """Identifier of the backend node."""
    objectId: "RemoteObjectId"
    """JavaScript object id of the node wrapper."""
    depth: "int"
    """The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the entire subtree or provide an integer larger than 0."""
    pierce: "bool"
    """Whether or not iframes and shadow roots should be traversed when returning the subtree (default is false)."""


class DescribeNodeReturns(TypedDict):
    node: "Node"
    """Node description."""
