# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DOM Domain Types"""

from typing import Any, List
from typing_extensions import Literal
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..page.types import FrameId

NodeId = int
"""Unique DOM node identifier."""


BackendNodeId = int
"""Unique DOM node identifier used to reference a node that may not have been pushed to the front-end."""


class BackendNode(TypedDict):
    """Backend node with a friendly name."""

    nodeType: "int"
    """<code>Node</code>'s nodeType."""
    nodeName: "str"
    """<code>Node</code>'s nodeName."""
    backendNodeId: "BackendNodeId"


PseudoType = Literal[
    "first-line",
    "first-letter",
    "before",
    "after",
    "backdrop",
    "selection",
    "first-line-inherited",
    "scrollbar",
    "scrollbar-thumb",
    "scrollbar-button",
    "scrollbar-track",
    "scrollbar-track-piece",
    "scrollbar-corner",
    "resizer",
    "input-list-button",
]
"""Pseudo element type."""


ShadowRootType = Literal["user-agent", "open", "closed"]
"""Shadow root type."""


class Node(TypedDict):
    """DOM interaction is implemented in terms of mirror objects that represent the actual DOM nodes. DOMNode is a base node mirror type."""

    nodeId: "NodeId"
    """Node identifier that is passed into the rest of the DOM messages as the <code>nodeId</code>. Backend will only push node with given <code>id</code> once. It is aware of all requested nodes and will only fire DOM events for nodes known to the client."""
    parentId: "NotRequired[NodeId]"
    """The id of the parent node if any."""
    backendNodeId: "BackendNodeId"
    """The BackendNodeId for this node."""
    nodeType: "int"
    """<code>Node</code>'s nodeType."""
    nodeName: "str"
    """<code>Node</code>'s nodeName."""
    localName: "str"
    """<code>Node</code>'s localName."""
    nodeValue: "str"
    """<code>Node</code>'s nodeValue."""
    childNodeCount: "NotRequired[int]"
    """Child count for <code>Container</code> nodes."""
    children: "NotRequired[List[Node]]"
    """Child nodes of this node when requested with children."""
    attributes: "NotRequired[List[str]]"
    """Attributes of the <code>Element</code> node in the form of flat array <code>[name1, value1, name2, value2]</code>."""
    documentURL: "NotRequired[str]"
    """Document URL that <code>Document</code> or <code>FrameOwner</code> node points to."""
    baseURL: "NotRequired[str]"
    """Base URL that <code>Document</code> or <code>FrameOwner</code> node uses for URL completion."""
    publicId: "NotRequired[str]"
    """<code>DocumentType</code>'s publicId."""
    systemId: "NotRequired[str]"
    """<code>DocumentType</code>'s systemId."""
    internalSubset: "NotRequired[str]"
    """<code>DocumentType</code>'s internalSubset."""
    xmlVersion: "NotRequired[str]"
    """<code>Document</code>'s XML version in case of XML documents."""
    name: "NotRequired[str]"
    """<code>Attr</code>'s name."""
    value: "NotRequired[str]"
    """<code>Attr</code>'s value."""
    pseudoType: "NotRequired[PseudoType]"
    """Pseudo element type for this node."""
    shadowRootType: "NotRequired[ShadowRootType]"
    """Shadow root type."""
    frameId: "NotRequired[FrameId]"
    """Frame ID for frame owner elements."""
    contentDocument: "NotRequired[Node]"
    """Content document for frame owner elements."""
    shadowRoots: "NotRequired[List[Node]]"
    """Shadow root list for given element host."""
    templateContent: "NotRequired[Node]"
    """Content document fragment for template elements."""
    pseudoElements: "NotRequired[List[Node]]"
    """Pseudo elements associated with this node."""
    importedDocument: "NotRequired[Node]"
    """Import document for the HTMLImport links."""
    distributedNodes: "NotRequired[List[BackendNode]]"
    """Distributed nodes for given insertion point."""
    isSVG: "NotRequired[bool]"
    """Whether the node is SVG."""


class RGBA(TypedDict):
    """A structure holding an RGBA color."""

    r: "int"
    """The red component, in the [0-255] range."""
    g: "int"
    """The green component, in the [0-255] range."""
    b: "int"
    """The blue component, in the [0-255] range."""
    a: "NotRequired[float]"
    """The alpha component, in the [0-1] range (default: 1)."""


Quad = List[float]
"""An array of quad vertices, x immediately followed by y for each point, points clock-wise."""


class BoxModel(TypedDict):
    """Box model."""

    content: "Quad"
    """Content box"""
    padding: "Quad"
    """Padding box"""
    border: "Quad"
    """Border box"""
    margin: "Quad"
    """Margin box"""
    width: "int"
    """Node width"""
    height: "int"
    """Node height"""
    shapeOutside: "NotRequired[ShapeOutsideInfo]"
    """Shape outside coordinates"""


class ShapeOutsideInfo(TypedDict):
    """CSS Shape Outside details."""

    bounds: "Quad"
    """Shape bounds"""
    shape: "List[Any]"
    """Shape coordinate details"""
    marginShape: "List[Any]"
    """Margin shape bounds"""


class Rect(TypedDict):
    """Rectangle."""

    x: "float"
    """X coordinate"""
    y: "float"
    """Y coordinate"""
    width: "float"
    """Rectangle width"""
    height: "float"
    """Rectangle height"""
