# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Animation Domain Types"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import BackendNodeId


class Animation(TypedDict):
    """Animation instance."""

    id: "str"
    """<code>Animation</code>'s id."""
    name: "str"
    """<code>Animation</code>'s name."""
    pausedState: "bool"
    """<code>Animation</code>'s internal paused state."""
    playState: "str"
    """<code>Animation</code>'s play state."""
    playbackRate: "float"
    """<code>Animation</code>'s playback rate."""
    startTime: "float"
    """<code>Animation</code>'s start time."""
    currentTime: "float"
    """<code>Animation</code>'s current time."""
    type: "str"
    """Animation type of <code>Animation</code>."""
    source: "NotRequired[AnimationEffect]"
    """<code>Animation</code>'s source animation node."""
    cssId: "NotRequired[str]"
    """A unique ID for <code>Animation</code> representing the sources that triggered this CSS animation/transition."""


class AnimationEffect(TypedDict):
    """AnimationEffect instance"""

    delay: "float"
    """<code>AnimationEffect</code>'s delay."""
    endDelay: "float"
    """<code>AnimationEffect</code>'s end delay."""
    iterationStart: "float"
    """<code>AnimationEffect</code>'s iteration start."""
    iterations: "float"
    """<code>AnimationEffect</code>'s iterations."""
    duration: "float"
    """<code>AnimationEffect</code>'s iteration duration."""
    direction: "str"
    """<code>AnimationEffect</code>'s playback direction."""
    fill: "str"
    """<code>AnimationEffect</code>'s fill mode."""
    backendNodeId: "NotRequired[BackendNodeId]"
    """<code>AnimationEffect</code>'s target node."""
    keyframesRule: "NotRequired[KeyframesRule]"
    """<code>AnimationEffect</code>'s keyframes."""
    easing: "str"
    """<code>AnimationEffect</code>'s timing function."""


class KeyframesRule(TypedDict):
    """Keyframes Rule"""

    name: "NotRequired[str]"
    """CSS keyframed animation's name."""
    keyframes: "List[KeyframeStyle]"
    """List of animation keyframes."""


class KeyframeStyle(TypedDict):
    """Keyframe Style"""

    offset: "str"
    """Keyframe's time offset."""
    easing: "str"
    """<code>AnimationEffect</code>'s timing function."""
