# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Runtime Domain Commands"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import CallArgument
    from .types import ExceptionDetails
    from .types import ExecutionContextId
    from .types import InternalPropertyDescriptor
    from .types import PropertyDescriptor
    from .types import RemoteObject
    from .types import RemoteObjectId
    from .types import ScriptId


class EvaluateParameters(TypedDict):
    expression: "str"
    """Expression to evaluate."""
    objectGroup: "NotRequired[str]"
    """Symbolic group name that can be used to release multiple objects."""
    includeCommandLineAPI: "NotRequired[bool]"
    """Determines whether Command Line API should be available during the evaluation."""
    silent: "NotRequired[bool]"
    """In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides <code>setPauseOnException</code> state."""
    contextId: "NotRequired[ExecutionContextId]"
    """Specifies in which execution context to perform evaluation. If the parameter is omitted the evaluation will be performed in the context of the inspected page."""
    returnByValue: "NotRequired[bool]"
    """Whether the result is expected to be a JSON object that should be sent by value."""
    generatePreview: "NotRequired[bool]"
    """Whether preview should be generated for the result."""
    userGesture: "NotRequired[bool]"
    """Whether execution should be treated as initiated by user in the UI."""
    awaitPromise: "NotRequired[bool]"
    """Whether execution should <code>await</code> for resulting value and return once awaited promise is resolved."""


class EvaluateReturns(TypedDict):
    result: "RemoteObject"
    """Evaluation result."""
    exceptionDetails: "ExceptionDetails"
    """Exception details."""


class AwaitPromiseParameters(TypedDict):
    promiseObjectId: "RemoteObjectId"
    """Identifier of the promise."""
    returnByValue: "NotRequired[bool]"
    """Whether the result is expected to be a JSON object that should be sent by value."""
    generatePreview: "NotRequired[bool]"
    """Whether preview should be generated for the result."""


class AwaitPromiseReturns(TypedDict):
    result: "RemoteObject"
    """Promise result. Will contain rejected value if promise was rejected."""
    exceptionDetails: "ExceptionDetails"
    """Exception details if stack strace is available."""


class CallFunctionOnParameters(TypedDict):
    functionDeclaration: "str"
    """Declaration of the function to call."""
    objectId: "NotRequired[RemoteObjectId]"
    """Identifier of the object to call function on. Either objectId or executionContextId should be specified."""
    arguments: "NotRequired[List[CallArgument]]"
    """Call arguments. All call arguments must belong to the same JavaScript world as the target object."""
    silent: "NotRequired[bool]"
    """In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides <code>setPauseOnException</code> state."""
    returnByValue: "NotRequired[bool]"
    """Whether the result is expected to be a JSON object which should be sent by value."""
    generatePreview: "NotRequired[bool]"
    """Whether preview should be generated for the result."""
    userGesture: "NotRequired[bool]"
    """Whether execution should be treated as initiated by user in the UI."""
    awaitPromise: "NotRequired[bool]"
    """Whether execution should <code>await</code> for resulting value and return once awaited promise is resolved."""
    executionContextId: "NotRequired[ExecutionContextId]"
    """Specifies execution context which global object will be used to call function on. Either executionContextId or objectId should be specified."""
    objectGroup: "NotRequired[str]"
    """Symbolic group name that can be used to release multiple objects. If objectGroup is not specified and objectId is, objectGroup will be inherited from object."""


class CallFunctionOnReturns(TypedDict):
    result: "RemoteObject"
    """Call result."""
    exceptionDetails: "ExceptionDetails"
    """Exception details."""


class GetPropertiesParameters(TypedDict):
    objectId: "RemoteObjectId"
    """Identifier of the object to return properties for."""
    ownProperties: "NotRequired[bool]"
    """If true, returns properties belonging only to the element itself, not to its prototype chain."""
    accessorPropertiesOnly: "NotRequired[bool]"
    """If true, returns accessor properties (with getter/setter) only; internal properties are not returned either."""
    generatePreview: "NotRequired[bool]"
    """Whether preview should be generated for the results."""


class GetPropertiesReturns(TypedDict):
    result: "List[PropertyDescriptor]"
    """Object properties."""
    internalProperties: "List[InternalPropertyDescriptor]"
    """Internal object properties (only of the element itself)."""
    exceptionDetails: "ExceptionDetails"
    """Exception details."""


class ReleaseObjectParameters(TypedDict):
    objectId: "RemoteObjectId"
    """Identifier of the object to release."""


class ReleaseObjectGroupParameters(TypedDict):
    objectGroup: "str"
    """Symbolic object group name."""


class SetCustomObjectFormatterEnabledParameters(TypedDict):
    enabled: "bool"


class CompileScriptParameters(TypedDict):
    expression: "str"
    """Expression to compile."""
    sourceURL: "str"
    """Source url to be set for the script."""
    persistScript: "bool"
    """Specifies whether the compiled script should be persisted."""
    executionContextId: "NotRequired[ExecutionContextId]"
    """Specifies in which execution context to perform script run. If the parameter is omitted the evaluation will be performed in the context of the inspected page."""


class CompileScriptReturns(TypedDict):
    scriptId: "ScriptId"
    """Id of the script."""
    exceptionDetails: "ExceptionDetails"
    """Exception details."""


class RunScriptParameters(TypedDict):
    scriptId: "ScriptId"
    """Id of the script to run."""
    executionContextId: "NotRequired[ExecutionContextId]"
    """Specifies in which execution context to perform script run. If the parameter is omitted the evaluation will be performed in the context of the inspected page."""
    objectGroup: "NotRequired[str]"
    """Symbolic group name that can be used to release multiple objects."""
    silent: "NotRequired[bool]"
    """In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides <code>setPauseOnException</code> state."""
    includeCommandLineAPI: "NotRequired[bool]"
    """Determines whether Command Line API should be available during the evaluation."""
    returnByValue: "NotRequired[bool]"
    """Whether the result is expected to be a JSON object which should be sent by value."""
    generatePreview: "NotRequired[bool]"
    """Whether preview should be generated for the result."""
    awaitPromise: "NotRequired[bool]"
    """Whether execution should <code>await</code> for resulting value and return once awaited promise is resolved."""


class RunScriptReturns(TypedDict):
    result: "RemoteObject"
    """Run result."""
    exceptionDetails: "ExceptionDetails"
    """Exception details."""


class QueryObjectsParameters(TypedDict):
    prototypeObjectId: "RemoteObjectId"
    """Identifier of the prototype to return objects for."""


class QueryObjectsReturns(TypedDict):
    objects: "RemoteObject"
    """Array with objects."""


class GlobalLexicalScopeNamesParameters(TypedDict, total=False):
    executionContextId: "ExecutionContextId"
    """Specifies in which execution context to lookup global scope variables."""


class GlobalLexicalScopeNamesReturns(TypedDict):
    names: "List[str]"
