# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Runtime Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import AwaitPromiseParameters
    from .commands import AwaitPromiseReturns
    from .commands import CallFunctionOnParameters
    from .commands import CallFunctionOnReturns
    from .commands import CompileScriptParameters
    from .commands import CompileScriptReturns
    from .commands import EvaluateParameters
    from .commands import EvaluateReturns
    from .commands import GetPropertiesParameters
    from .commands import GetPropertiesReturns
    from .commands import GlobalLexicalScopeNamesParameters
    from .commands import GlobalLexicalScopeNamesReturns
    from .commands import QueryObjectsParameters
    from .commands import QueryObjectsReturns
    from .commands import ReleaseObjectGroupParameters
    from .commands import ReleaseObjectParameters
    from .commands import RunScriptParameters
    from .commands import RunScriptReturns
    from .commands import SetCustomObjectFormatterEnabledParameters


class RuntimeClient:
    """Client for Runtime domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def evaluate(
        self,
        params: "EvaluateParameters",
        session_id: Optional[str] = None,
    ) -> "EvaluateReturns":
        """Evaluates expression on global object."""
        return cast(
            "EvaluateReturns",
            await self._client.send_raw(
                method="Runtime.evaluate",
                params=params,
                session_id=session_id,
            ),
        )

    async def awaitPromise(
        self,
        params: "AwaitPromiseParameters",
        session_id: Optional[str] = None,
    ) -> "AwaitPromiseReturns":
        """Add handler to promise with given promise object id."""
        return cast(
            "AwaitPromiseReturns",
            await self._client.send_raw(
                method="Runtime.awaitPromise",
                params=params,
                session_id=session_id,
            ),
        )

    async def callFunctionOn(
        self,
        params: "CallFunctionOnParameters",
        session_id: Optional[str] = None,
    ) -> "CallFunctionOnReturns":
        """Calls function with given declaration on the given object. Object group of the result is inherited from the target object."""
        return cast(
            "CallFunctionOnReturns",
            await self._client.send_raw(
                method="Runtime.callFunctionOn",
                params=params,
                session_id=session_id,
            ),
        )

    async def getProperties(
        self,
        params: "GetPropertiesParameters",
        session_id: Optional[str] = None,
    ) -> "GetPropertiesReturns":
        """Returns properties of a given object. Object group of the result is inherited from the target object."""
        return cast(
            "GetPropertiesReturns",
            await self._client.send_raw(
                method="Runtime.getProperties",
                params=params,
                session_id=session_id,
            ),
        )

    async def releaseObject(
        self,
        params: "ReleaseObjectParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Releases remote object with given id."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Runtime.releaseObject",
                params=params,
                session_id=session_id,
            ),
        )

    async def releaseObjectGroup(
        self,
        params: "ReleaseObjectGroupParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Releases all remote objects that belong to a given group."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Runtime.releaseObjectGroup",
                params=params,
                session_id=session_id,
            ),
        )

    async def runIfWaitingForDebugger(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Tells inspected instance to run if it was waiting for debugger to attach."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Runtime.runIfWaitingForDebugger",
                params=params,
                session_id=session_id,
            ),
        )

    async def enable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enables reporting of execution contexts creation by means of <code>executionContextCreated</code> event. When the reporting gets enabled the event will be sent immediately for each existing execution context."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Runtime.enable",
                params=params,
                session_id=session_id,
            ),
        )

    async def disable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Disables reporting of execution contexts creation."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Runtime.disable",
                params=params,
                session_id=session_id,
            ),
        )

    async def discardConsoleEntries(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Discards collected exceptions and console API calls."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Runtime.discardConsoleEntries",
                params=params,
                session_id=session_id,
            ),
        )

    async def setCustomObjectFormatterEnabled(
        self,
        params: "SetCustomObjectFormatterEnabledParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Runtime.setCustomObjectFormatterEnabled",
                params=params,
                session_id=session_id,
            ),
        )

    async def compileScript(
        self,
        params: "CompileScriptParameters",
        session_id: Optional[str] = None,
    ) -> "CompileScriptReturns":
        """Compiles expression."""
        return cast(
            "CompileScriptReturns",
            await self._client.send_raw(
                method="Runtime.compileScript",
                params=params,
                session_id=session_id,
            ),
        )

    async def runScript(
        self,
        params: "RunScriptParameters",
        session_id: Optional[str] = None,
    ) -> "RunScriptReturns":
        """Runs script with given id in a given context."""
        return cast(
            "RunScriptReturns",
            await self._client.send_raw(
                method="Runtime.runScript",
                params=params,
                session_id=session_id,
            ),
        )

    async def queryObjects(
        self,
        params: "QueryObjectsParameters",
        session_id: Optional[str] = None,
    ) -> "QueryObjectsReturns":
        return cast(
            "QueryObjectsReturns",
            await self._client.send_raw(
                method="Runtime.queryObjects",
                params=params,
                session_id=session_id,
            ),
        )

    async def globalLexicalScopeNames(
        self,
        params: Optional["GlobalLexicalScopeNamesParameters"] = None,
        session_id: Optional[str] = None,
    ) -> "GlobalLexicalScopeNamesReturns":
        """Returns all let, const and class variables from global scope."""
        return cast(
            "GlobalLexicalScopeNamesReturns",
            await self._client.send_raw(
                method="Runtime.globalLexicalScopeNames",
                params=params,
                session_id=session_id,
            ),
        )
