# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Database Domain Commands"""

from typing import Any, List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import DatabaseId
    from .types import Error


class GetDatabaseTableNamesParameters(TypedDict):
    databaseId: "DatabaseId"


class GetDatabaseTableNamesReturns(TypedDict):
    tableNames: "List[str]"


class ExecuteSQLParameters(TypedDict):
    databaseId: "DatabaseId"
    query: "str"


class ExecuteSQLReturns(TypedDict):
    columnNames: "List[str]"
    values: "List[Any]"
    sqlError: "Error"
