# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Database Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import ExecuteSQLParameters
    from .commands import ExecuteSQLReturns
    from .commands import GetDatabaseTableNamesParameters
    from .commands import GetDatabaseTableNamesReturns


class DatabaseClient:
    """Client for Database domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def enable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enables database tracking, database events will now be delivered to the client."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Database.enable",
                params=params,
                session_id=session_id,
            ),
        )

    async def disable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Disables database tracking, prevents database events from being sent to the client."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Database.disable",
                params=params,
                session_id=session_id,
            ),
        )

    async def getDatabaseTableNames(
        self,
        params: "GetDatabaseTableNamesParameters",
        session_id: Optional[str] = None,
    ) -> "GetDatabaseTableNamesReturns":
        return cast(
            "GetDatabaseTableNamesReturns",
            await self._client.send_raw(
                method="Database.getDatabaseTableNames",
                params=params,
                session_id=session_id,
            ),
        )

    async def executeSQL(
        self,
        params: "ExecuteSQLParameters",
        session_id: Optional[str] = None,
    ) -> "ExecuteSQLReturns":
        return cast(
            "ExecuteSQLReturns",
            await self._client.send_raw(
                method="Database.executeSQL",
                params=params,
                session_id=session_id,
            ),
        )
