# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Database Domain Event Registration"""

from typing import Callable, Optional

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import AddDatabaseEvent


class DatabaseRegistration:
    """Event registration interface for Database domain."""

    def __init__(self, registry: "EventRegistry"):
        self._registry = registry
        self._domain = "Database"

    def addDatabase(
        self,
        callback: Callable[["AddDatabaseEvent", Optional[str]], None],
    ) -> None:
        """
        Register a callback for addDatabase events.

        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("Database.addDatabase", callback)
