# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Database Domain Types"""

from typing_extensions import TypedDict

DatabaseId = str
"""Unique identifier of Database object."""


class Database(TypedDict):
    """Database object."""

    id: "DatabaseId"
    """Database ID."""
    domain: "str"
    """Database domain."""
    name: "str"
    """Database name."""
    version: "str"
    """Database version."""


class Error(TypedDict):
    """Database error."""

    message: "str"
    """Error message."""
    code: "int"
    """Error code."""
