# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Accessibility Domain Commands"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import NodeId
    from .types import AXNode


class GetPartialAXTreeParameters(TypedDict):
    nodeId: "NodeId"
    """ID of node to get the partial accessibility tree for."""
    fetchRelatives: "NotRequired[bool]"
    """Whether to fetch this nodes ancestors, siblings and children. Defaults to true."""


class GetPartialAXTreeReturns(TypedDict):
    nodes: "List[AXNode]"
    """The <code>Accessibility.AXNode</code> for this DOM node, if it exists, plus its ancestors, siblings and children, if requested."""
