# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Accessibility Domain Library"""

from typing import Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import GetPartialAXTreeParameters
    from .commands import GetPartialAXTreeReturns


class AccessibilityClient:
    """Client for Accessibility domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def getPartialAXTree(
        self,
        params: "GetPartialAXTreeParameters",
        session_id: Optional[str] = None,
    ) -> "GetPartialAXTreeReturns":
        """Fetches the accessibility node and partial accessibility tree for this DOM node, if it exists."""
        return cast(
            "GetPartialAXTreeReturns",
            await self._client.send_raw(
                method="Accessibility.getPartialAXTree",
                params=params,
                session_id=session_id,
            ),
        )
