# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Input Domain Types"""

from typing_extensions import Literal
from typing_extensions import NotRequired, TypedDict


class TouchPoint(TypedDict):
    x: "float"
    """X coordinate of the event relative to the main frame's viewport in CSS pixels."""
    y: "float"
    """Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to the top of the viewport and Y increases as it proceeds towards the bottom of the viewport."""
    radiusX: "NotRequired[float]"
    """X radius of the touch area (default: 1.0)."""
    radiusY: "NotRequired[float]"
    """Y radius of the touch area (default: 1.0)."""
    rotationAngle: "NotRequired[float]"
    """Rotation angle (default: 0.0)."""
    force: "NotRequired[float]"
    """Force (default: 1.0)."""
    id: "NotRequired[float]"
    """Identifier used to track touch sources between events, must be unique within an event."""


GestureSourceType = Literal["default", "touch", "mouse"]


TimeSinceEpoch = float
"""UTC time in seconds, counted from January 1, 1970."""
