# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DOMSnapshot Domain Commands"""

from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import ComputedStyle
    from .types import DOMNode
    from .types import LayoutTreeNode


class GetSnapshotParameters(TypedDict):
    computedStyleWhitelist: "List[str]"
    """Whitelist of computed styles to return."""


class GetSnapshotReturns(TypedDict):
    domNodes: "List[DOMNode]"
    """The nodes in the DOM tree. The DOMNode at index 0 corresponds to the root document."""
    layoutTreeNodes: "List[LayoutTreeNode]"
    """The nodes in the layout tree."""
    computedStyles: "List[ComputedStyle]"
    """Whitelisted ComputedStyle properties for each node in the layout tree."""
