# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DOMSnapshot Domain Types"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import BackendNodeId
    from ..dom.types import PseudoType
    from ..dom.types import Rect
    from ..page.types import FrameId


class DOMNode(TypedDict):
    """A Node in the DOM tree."""

    nodeType: "int"
    """<code>Node</code>'s nodeType."""
    nodeName: "str"
    """<code>Node</code>'s nodeName."""
    nodeValue: "str"
    """<code>Node</code>'s nodeValue."""
    textValue: "NotRequired[str]"
    """Only set for textarea elements, contains the text value."""
    inputValue: "NotRequired[str]"
    """Only set for input elements, contains the input's associated text value."""
    inputChecked: "NotRequired[bool]"
    """Only set for radio and checkbox input elements, indicates if the element has been checked"""
    optionSelected: "NotRequired[bool]"
    """Only set for option elements, indicates if the element has been selected"""
    backendNodeId: "BackendNodeId"
    """<code>Node</code>'s id, corresponds to DOM.Node.backendNodeId."""
    childNodeIndexes: "NotRequired[List[int]]"
    """The indexes of the node's child nodes in the <code>domNodes</code> array returned by <code>getSnapshot</code>, if any."""
    attributes: "NotRequired[List[NameValue]]"
    """Attributes of an <code>Element</code> node."""
    pseudoElementIndexes: "NotRequired[List[int]]"
    """Indexes of pseudo elements associated with this node in the <code>domNodes</code> array returned by <code>getSnapshot</code>, if any."""
    layoutNodeIndex: "NotRequired[int]"
    """The index of the node's related layout tree node in the <code>layoutTreeNodes</code> array returned by <code>getSnapshot</code>, if any."""
    documentURL: "NotRequired[str]"
    """Document URL that <code>Document</code> or <code>FrameOwner</code> node points to."""
    baseURL: "NotRequired[str]"
    """Base URL that <code>Document</code> or <code>FrameOwner</code> node uses for URL completion."""
    contentLanguage: "NotRequired[str]"
    """Only set for documents, contains the document's content language."""
    documentEncoding: "NotRequired[str]"
    """Only set for documents, contains the document's character set encoding."""
    publicId: "NotRequired[str]"
    """<code>DocumentType</code> node's publicId."""
    systemId: "NotRequired[str]"
    """<code>DocumentType</code> node's systemId."""
    frameId: "NotRequired[FrameId]"
    """Frame ID for frame owner elements and also for the document node."""
    contentDocumentIndex: "NotRequired[int]"
    """The index of a frame owner element's content document in the <code>domNodes</code> array returned by <code>getSnapshot</code>, if any."""
    importedDocumentIndex: "NotRequired[int]"
    """Index of the imported document's node of a link element in the <code>domNodes</code> array returned by <code>getSnapshot</code>, if any."""
    templateContentIndex: "NotRequired[int]"
    """Index of the content node of a template element in the <code>domNodes</code> array returned by <code>getSnapshot</code>."""
    pseudoType: "NotRequired[PseudoType]"
    """Type of a pseudo element node."""
    isClickable: "NotRequired[bool]"
    """Whether this DOM node responds to mouse clicks. This includes nodes that have had click event listeners attached via JavaScript as well as anchor tags that naturally navigate when clicked."""


class InlineTextBox(TypedDict):
    """Details of post layout rendered text positions. The exact layout should not be regarded as stable and may change between versions."""

    boundingBox: "Rect"
    """The absolute position bounding box."""
    startCharacterIndex: "int"
    """The starting index in characters, for this post layout textbox substring."""
    numCharacters: "int"
    """The number of characters in this post layout textbox substring."""


class LayoutTreeNode(TypedDict):
    """Details of an element in the DOM tree with a LayoutObject."""

    domNodeIndex: "int"
    """The index of the related DOM node in the <code>domNodes</code> array returned by <code>getSnapshot</code>."""
    boundingBox: "Rect"
    """The absolute position bounding box."""
    layoutText: "NotRequired[str]"
    """Contents of the LayoutText, if any."""
    inlineTextNodes: "NotRequired[List[InlineTextBox]]"
    """The post-layout inline text nodes, if any."""
    styleIndex: "NotRequired[int]"
    """Index into the <code>computedStyles</code> array returned by <code>getSnapshot</code>."""


class ComputedStyle(TypedDict):
    """A subset of the full ComputedStyle as defined by the request whitelist."""

    properties: "List[NameValue]"
    """Name/value pairs of computed style properties."""


class NameValue(TypedDict):
    """A name/value pair."""

    name: "str"
    """Attribute/property name."""
    value: "str"
    """Attribute/property value."""
