# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP ServiceWorker Domain Commands"""

from typing_extensions import TypedDict


class UnregisterParameters(TypedDict):
    scopeURL: "str"


class UpdateRegistrationParameters(TypedDict):
    scopeURL: "str"


class StartWorkerParameters(TypedDict):
    scopeURL: "str"


class SkipWaitingParameters(TypedDict):
    scopeURL: "str"


class StopWorkerParameters(TypedDict):
    versionId: "str"


class InspectWorkerParameters(TypedDict):
    versionId: "str"


class SetForceUpdateOnPageLoadParameters(TypedDict):
    forceUpdateOnPageLoad: "bool"


class DeliverPushMessageParameters(TypedDict):
    origin: "str"
    registrationId: "str"
    data: "str"


class DispatchSyncEventParameters(TypedDict):
    origin: "str"
    registrationId: "str"
    tag: "str"
    lastChance: "bool"
