# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP CacheStorage Domain Commands"""

from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import Cache
    from .types import CacheId
    from .types import CachedResponse
    from .types import DataEntry


class RequestCacheNamesParameters(TypedDict):
    securityOrigin: "str"
    """Security origin."""


class RequestCacheNamesReturns(TypedDict):
    caches: "List[Cache]"
    """Caches for the security origin."""


class RequestEntriesParameters(TypedDict):
    cacheId: "CacheId"
    """ID of cache to get entries from."""
    skipCount: "int"
    """Number of records to skip."""
    pageSize: "int"
    """Number of records to fetch."""


class RequestEntriesReturns(TypedDict):
    cacheDataEntries: "List[DataEntry]"
    """Array of object store data entries."""
    hasMore: "bool"
    """If true, there are more entries to fetch in the given range."""


class DeleteCacheParameters(TypedDict):
    cacheId: "CacheId"
    """Id of cache for deletion."""


class DeleteEntryParameters(TypedDict):
    cacheId: "CacheId"
    """Id of cache where the entry will be deleted."""
    request: "str"
    """URL spec of the request."""


class RequestCachedResponseParameters(TypedDict):
    cacheId: "CacheId"
    """Id of cache that contains the enty."""
    requestURL: "str"
    """URL spec of the request."""


class RequestCachedResponseReturns(TypedDict):
    response: "CachedResponse"
    """Response read from the cache."""
