# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP CacheStorage Domain Types"""

from typing import List
from typing_extensions import TypedDict

CacheId = str
"""Unique identifier of the Cache object."""


class DataEntry(TypedDict):
    """Data entry."""

    requestURL: "str"
    """Request URL."""
    requestMethod: "str"
    """Request method."""
    requestHeaders: "List[Header]"
    """Request headers"""
    responseTime: "float"
    """Number of seconds since epoch."""
    responseStatus: "int"
    """HTTP response status code."""
    responseStatusText: "str"
    """HTTP response status text."""
    responseHeaders: "List[Header]"
    """Response headers"""


class Cache(TypedDict):
    """Cache identifier."""

    cacheId: "CacheId"
    """An opaque unique id of the cache."""
    securityOrigin: "str"
    """Security origin of the cache."""
    cacheName: "str"
    """The name of the cache."""


class Header(TypedDict):
    name: "str"
    value: "str"


class CachedResponse(TypedDict):
    """Cached response"""

    body: "str"
    """Entry content, base64-encoded."""
