# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DOMStorage Domain Types"""

from typing import List
from typing_extensions import TypedDict


class StorageId(TypedDict):
    """DOM Storage identifier."""

    securityOrigin: "str"
    """Security origin for the storage."""
    isLocalStorage: "bool"
    """Whether the storage is local storage (not session storage)."""


Item = List[str]
"""DOM Storage item."""
