# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Tracing Domain Commands"""

from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import TraceConfig


class StartParameters(TypedDict, total=False):
    categories: "str"
    """Category/tag filter"""
    options: "str"
    """Tracing options"""
    bufferUsageReportingInterval: "float"
    """If set, the agent will issue bufferUsage events at this interval, specified in milliseconds"""
    transferMode: "str"
    """Whether to report trace events as series of dataCollected events or to save trace to a stream (defaults to <code>ReportEvents</code>)."""
    traceConfig: "TraceConfig"


class GetCategoriesReturns(TypedDict):
    categories: "List[str]"
    """A list of supported tracing categories."""


class RequestMemoryDumpReturns(TypedDict):
    dumpGuid: "str"
    """GUID of the resulting global memory dump."""
    success: "bool"
    """True iff the global memory dump succeeded."""


class RecordClockSyncMarkerParameters(TypedDict):
    syncId: "str"
    """The ID of this clock sync marker"""
