# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Tracing Domain Types"""

from typing import List
from typing_extensions import TypedDict


class MemoryDumpConfig(TypedDict):
    """Configuration for memory dump. Used only when \"memory-infra\" category is enabled."""


class TraceConfig(TypedDict, total=False):
    recordMode: "str"
    """Controls how the trace buffer stores data."""
    enableSampling: "bool"
    """Turns on JavaScript stack sampling."""
    enableSystrace: "bool"
    """Turns on system tracing."""
    enableArgumentFilter: "bool"
    """Turns on argument filter."""
    includedCategories: "List[str]"
    """Included category filters."""
    excludedCategories: "List[str]"
    """Excluded category filters."""
    syntheticDelays: "List[str]"
    """Configuration to synthesize the delays in tracing."""
    memoryDumpConfig: "MemoryDumpConfig"
    """Configuration for memory dump triggers. Used only when \"memory-infra\" category is enabled."""
