# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP CSS Domain Commands"""

from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import NodeId
    from ..page.types import FrameId
    from .types import CSSComputedStyleProperty
    from .types import CSSKeyframesRule
    from .types import CSSMedia
    from .types import CSSRule
    from .types import CSSStyle
    from .types import InheritedStyleEntry
    from .types import PlatformFontUsage
    from .types import PseudoElementMatches
    from .types import RuleMatch
    from .types import RuleUsage
    from .types import SelectorList
    from .types import SourceRange
    from .types import StyleDeclarationEdit
    from .types import StyleSheetId
    from .types import Value


class GetMatchedStylesForNodeParameters(TypedDict):
    nodeId: "NodeId"


class GetMatchedStylesForNodeReturns(TypedDict):
    inlineStyle: "CSSStyle"
    """Inline style for the specified DOM node."""
    attributesStyle: "CSSStyle"
    """Attribute-defined element style (e.g. resulting from \"width=20 height=100%\")."""
    matchedCSSRules: "List[RuleMatch]"
    """CSS rules matching this node, from all applicable stylesheets."""
    pseudoElements: "List[PseudoElementMatches]"
    """Pseudo style matches for this node."""
    inherited: "List[InheritedStyleEntry]"
    """A chain of inherited styles (from the immediate node parent up to the DOM tree root)."""
    cssKeyframesRules: "List[CSSKeyframesRule]"
    """A list of CSS keyframed animations matching this node."""


class GetInlineStylesForNodeParameters(TypedDict):
    nodeId: "NodeId"


class GetInlineStylesForNodeReturns(TypedDict):
    inlineStyle: "CSSStyle"
    """Inline style for the specified DOM node."""
    attributesStyle: "CSSStyle"
    """Attribute-defined element style (e.g. resulting from \"width=20 height=100%\")."""


class GetComputedStyleForNodeParameters(TypedDict):
    nodeId: "NodeId"


class GetComputedStyleForNodeReturns(TypedDict):
    computedStyle: "List[CSSComputedStyleProperty]"
    """Computed style for the specified DOM node."""


class GetPlatformFontsForNodeParameters(TypedDict):
    nodeId: "NodeId"


class GetPlatformFontsForNodeReturns(TypedDict):
    fonts: "List[PlatformFontUsage]"
    """Usage statistics for every employed platform font."""


class GetStyleSheetTextParameters(TypedDict):
    styleSheetId: "StyleSheetId"


class GetStyleSheetTextReturns(TypedDict):
    text: "str"
    """The stylesheet text."""


class CollectClassNamesParameters(TypedDict):
    styleSheetId: "StyleSheetId"


class CollectClassNamesReturns(TypedDict):
    classNames: "List[str]"
    """Class name list."""


class SetStyleSheetTextParameters(TypedDict):
    styleSheetId: "StyleSheetId"
    text: "str"


class SetStyleSheetTextReturns(TypedDict):
    sourceMapURL: "str"
    """URL of source map associated with script (if any)."""


class SetRuleSelectorParameters(TypedDict):
    styleSheetId: "StyleSheetId"
    range: "SourceRange"
    selector: "str"


class SetRuleSelectorReturns(TypedDict):
    selectorList: "SelectorList"
    """The resulting selector list after modification."""


class SetKeyframeKeyParameters(TypedDict):
    styleSheetId: "StyleSheetId"
    range: "SourceRange"
    keyText: "str"


class SetKeyframeKeyReturns(TypedDict):
    keyText: "Value"
    """The resulting key text after modification."""


class SetStyleTextsParameters(TypedDict):
    edits: "List[StyleDeclarationEdit]"


class SetStyleTextsReturns(TypedDict):
    styles: "List[CSSStyle]"
    """The resulting styles after modification."""


class SetMediaTextParameters(TypedDict):
    styleSheetId: "StyleSheetId"
    range: "SourceRange"
    text: "str"


class SetMediaTextReturns(TypedDict):
    media: "CSSMedia"
    """The resulting CSS media rule after modification."""


class CreateStyleSheetParameters(TypedDict):
    frameId: "FrameId"
    """Identifier of the frame where \"via-inspector\" stylesheet should be created."""


class CreateStyleSheetReturns(TypedDict):
    styleSheetId: "StyleSheetId"
    """Identifier of the created \"via-inspector\" stylesheet."""


class AddRuleParameters(TypedDict):
    styleSheetId: "StyleSheetId"
    """The css style sheet identifier where a new rule should be inserted."""
    ruleText: "str"
    """The text of a new rule."""
    location: "SourceRange"
    """Text position of a new rule in the target style sheet."""


class AddRuleReturns(TypedDict):
    rule: "CSSRule"
    """The newly created rule."""


class ForcePseudoStateParameters(TypedDict):
    nodeId: "NodeId"
    """The element id for which to force the pseudo state."""
    forcedPseudoClasses: "List[str]"
    """Element pseudo classes to force when computing the element's style."""


class GetMediaQueriesReturns(TypedDict):
    medias: "List[CSSMedia]"


class SetEffectivePropertyValueForNodeParameters(TypedDict):
    nodeId: "NodeId"
    """The element id for which to set property."""
    propertyName: "str"
    value: "str"


class GetBackgroundColorsParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to get background colors for."""


class GetBackgroundColorsReturns(TypedDict):
    backgroundColors: "List[str]"
    """The range of background colors behind this element, if it contains any visible text. If no visible text is present, this will be undefined. In the case of a flat background color, this will consist of simply that color. In the case of a gradient, this will consist of each of the color stops. For anything more complicated, this will be an empty array. Images will be ignored (as if the image had failed to load)."""
    computedFontSize: "str"
    """The computed font size for this node, as a CSS computed value string (e.g. '12px')."""
    computedFontWeight: "str"
    """The computed font weight for this node, as a CSS computed value string (e.g. 'normal' or '100')."""
    computedBodyFontSize: "str"
    """The computed font size for the document body, as a computed CSS value string (e.g. '16px')."""


class TakeCoverageDeltaReturns(TypedDict):
    coverage: "List[RuleUsage]"


class StopRuleUsageTrackingReturns(TypedDict):
    ruleUsage: "List[RuleUsage]"
