# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP CSS Domain Events"""

from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import CSSStyleSheetHeader
    from .types import StyleSheetId

"""Fires whenever a MediaQuery result changes (for example, after a browser window has been resized.) The current implementation considers only viewport-dependent media features."""


class MediaQueryResultChangedEvent(TypedDict):
    pass


"""Fires whenever a web font gets loaded."""


class FontsUpdatedEvent(TypedDict):
    pass


"""Fired whenever a stylesheet is changed as a result of the client operation."""


class StyleSheetChangedEvent(TypedDict):
    styleSheetId: "StyleSheetId"


"""Fired whenever an active document stylesheet is added."""


class StyleSheetAddedEvent(TypedDict):
    header: "CSSStyleSheetHeader"
    """Added stylesheet metainfo."""


"""Fired whenever an active document stylesheet is removed."""


class StyleSheetRemovedEvent(TypedDict):
    styleSheetId: "StyleSheetId"
    """Identifier of the removed stylesheet."""
