# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP CSS Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import AddRuleParameters
    from .commands import AddRuleReturns
    from .commands import CollectClassNamesParameters
    from .commands import CollectClassNamesReturns
    from .commands import CreateStyleSheetParameters
    from .commands import CreateStyleSheetReturns
    from .commands import ForcePseudoStateParameters
    from .commands import GetBackgroundColorsParameters
    from .commands import GetBackgroundColorsReturns
    from .commands import GetComputedStyleForNodeParameters
    from .commands import GetComputedStyleForNodeReturns
    from .commands import GetInlineStylesForNodeParameters
    from .commands import GetInlineStylesForNodeReturns
    from .commands import GetMatchedStylesForNodeParameters
    from .commands import GetMatchedStylesForNodeReturns
    from .commands import GetMediaQueriesReturns
    from .commands import GetPlatformFontsForNodeParameters
    from .commands import GetPlatformFontsForNodeReturns
    from .commands import GetStyleSheetTextParameters
    from .commands import GetStyleSheetTextReturns
    from .commands import SetEffectivePropertyValueForNodeParameters
    from .commands import SetKeyframeKeyParameters
    from .commands import SetKeyframeKeyReturns
    from .commands import SetMediaTextParameters
    from .commands import SetMediaTextReturns
    from .commands import SetRuleSelectorParameters
    from .commands import SetRuleSelectorReturns
    from .commands import SetStyleSheetTextParameters
    from .commands import SetStyleSheetTextReturns
    from .commands import SetStyleTextsParameters
    from .commands import SetStyleTextsReturns
    from .commands import StopRuleUsageTrackingReturns
    from .commands import TakeCoverageDeltaReturns


class CSSClient:
    """Client for CSS domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def enable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enables the CSS agent for the given page. Clients should not assume that the CSS agent has been enabled until the result of this command is received."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="CSS.enable",
                params=params,
                session_id=session_id,
            ),
        )

    async def disable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Disables the CSS agent for the given page."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="CSS.disable",
                params=params,
                session_id=session_id,
            ),
        )

    async def getMatchedStylesForNode(
        self,
        params: "GetMatchedStylesForNodeParameters",
        session_id: Optional[str] = None,
    ) -> "GetMatchedStylesForNodeReturns":
        """Returns requested styles for a DOM node identified by <code>nodeId</code>."""
        return cast(
            "GetMatchedStylesForNodeReturns",
            await self._client.send_raw(
                method="CSS.getMatchedStylesForNode",
                params=params,
                session_id=session_id,
            ),
        )

    async def getInlineStylesForNode(
        self,
        params: "GetInlineStylesForNodeParameters",
        session_id: Optional[str] = None,
    ) -> "GetInlineStylesForNodeReturns":
        """Returns the styles defined inline (explicitly in the \"style\" attribute and implicitly, using DOM attributes) for a DOM node identified by <code>nodeId</code>."""
        return cast(
            "GetInlineStylesForNodeReturns",
            await self._client.send_raw(
                method="CSS.getInlineStylesForNode",
                params=params,
                session_id=session_id,
            ),
        )

    async def getComputedStyleForNode(
        self,
        params: "GetComputedStyleForNodeParameters",
        session_id: Optional[str] = None,
    ) -> "GetComputedStyleForNodeReturns":
        """Returns the computed style for a DOM node identified by <code>nodeId</code>."""
        return cast(
            "GetComputedStyleForNodeReturns",
            await self._client.send_raw(
                method="CSS.getComputedStyleForNode",
                params=params,
                session_id=session_id,
            ),
        )

    async def getPlatformFontsForNode(
        self,
        params: "GetPlatformFontsForNodeParameters",
        session_id: Optional[str] = None,
    ) -> "GetPlatformFontsForNodeReturns":
        """Requests information about platform fonts which we used to render child TextNodes in the given node."""
        return cast(
            "GetPlatformFontsForNodeReturns",
            await self._client.send_raw(
                method="CSS.getPlatformFontsForNode",
                params=params,
                session_id=session_id,
            ),
        )

    async def getStyleSheetText(
        self,
        params: "GetStyleSheetTextParameters",
        session_id: Optional[str] = None,
    ) -> "GetStyleSheetTextReturns":
        """Returns the current textual content and the URL for a stylesheet."""
        return cast(
            "GetStyleSheetTextReturns",
            await self._client.send_raw(
                method="CSS.getStyleSheetText",
                params=params,
                session_id=session_id,
            ),
        )

    async def collectClassNames(
        self,
        params: "CollectClassNamesParameters",
        session_id: Optional[str] = None,
    ) -> "CollectClassNamesReturns":
        """Returns all class names from specified stylesheet."""
        return cast(
            "CollectClassNamesReturns",
            await self._client.send_raw(
                method="CSS.collectClassNames",
                params=params,
                session_id=session_id,
            ),
        )

    async def setStyleSheetText(
        self,
        params: "SetStyleSheetTextParameters",
        session_id: Optional[str] = None,
    ) -> "SetStyleSheetTextReturns":
        """Sets the new stylesheet text."""
        return cast(
            "SetStyleSheetTextReturns",
            await self._client.send_raw(
                method="CSS.setStyleSheetText",
                params=params,
                session_id=session_id,
            ),
        )

    async def setRuleSelector(
        self,
        params: "SetRuleSelectorParameters",
        session_id: Optional[str] = None,
    ) -> "SetRuleSelectorReturns":
        """Modifies the rule selector."""
        return cast(
            "SetRuleSelectorReturns",
            await self._client.send_raw(
                method="CSS.setRuleSelector",
                params=params,
                session_id=session_id,
            ),
        )

    async def setKeyframeKey(
        self,
        params: "SetKeyframeKeyParameters",
        session_id: Optional[str] = None,
    ) -> "SetKeyframeKeyReturns":
        """Modifies the keyframe rule key text."""
        return cast(
            "SetKeyframeKeyReturns",
            await self._client.send_raw(
                method="CSS.setKeyframeKey",
                params=params,
                session_id=session_id,
            ),
        )

    async def setStyleTexts(
        self,
        params: "SetStyleTextsParameters",
        session_id: Optional[str] = None,
    ) -> "SetStyleTextsReturns":
        """Applies specified style edits one after another in the given order."""
        return cast(
            "SetStyleTextsReturns",
            await self._client.send_raw(
                method="CSS.setStyleTexts",
                params=params,
                session_id=session_id,
            ),
        )

    async def setMediaText(
        self,
        params: "SetMediaTextParameters",
        session_id: Optional[str] = None,
    ) -> "SetMediaTextReturns":
        """Modifies the rule selector."""
        return cast(
            "SetMediaTextReturns",
            await self._client.send_raw(
                method="CSS.setMediaText",
                params=params,
                session_id=session_id,
            ),
        )

    async def createStyleSheet(
        self,
        params: "CreateStyleSheetParameters",
        session_id: Optional[str] = None,
    ) -> "CreateStyleSheetReturns":
        """Creates a new special \"via-inspector\" stylesheet in the frame with given <code>frameId</code>."""
        return cast(
            "CreateStyleSheetReturns",
            await self._client.send_raw(
                method="CSS.createStyleSheet",
                params=params,
                session_id=session_id,
            ),
        )

    async def addRule(
        self,
        params: "AddRuleParameters",
        session_id: Optional[str] = None,
    ) -> "AddRuleReturns":
        """Inserts a new rule with the given <code>ruleText</code> in a stylesheet with given <code>styleSheetId</code>, at the position specified by <code>location</code>."""
        return cast(
            "AddRuleReturns",
            await self._client.send_raw(
                method="CSS.addRule",
                params=params,
                session_id=session_id,
            ),
        )

    async def forcePseudoState(
        self,
        params: "ForcePseudoStateParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Ensures that the given node will have specified pseudo-classes whenever its style is computed by the browser."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="CSS.forcePseudoState",
                params=params,
                session_id=session_id,
            ),
        )

    async def getMediaQueries(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetMediaQueriesReturns":
        """Returns all media queries parsed by the rendering engine."""
        return cast(
            "GetMediaQueriesReturns",
            await self._client.send_raw(
                method="CSS.getMediaQueries",
                params=params,
                session_id=session_id,
            ),
        )

    async def setEffectivePropertyValueForNode(
        self,
        params: "SetEffectivePropertyValueForNodeParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Find a rule with the given active property for the given node and set the new value for this property"""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="CSS.setEffectivePropertyValueForNode",
                params=params,
                session_id=session_id,
            ),
        )

    async def getBackgroundColors(
        self,
        params: "GetBackgroundColorsParameters",
        session_id: Optional[str] = None,
    ) -> "GetBackgroundColorsReturns":
        return cast(
            "GetBackgroundColorsReturns",
            await self._client.send_raw(
                method="CSS.getBackgroundColors",
                params=params,
                session_id=session_id,
            ),
        )

    async def startRuleUsageTracking(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enables the selector recording."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="CSS.startRuleUsageTracking",
                params=params,
                session_id=session_id,
            ),
        )

    async def takeCoverageDelta(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "TakeCoverageDeltaReturns":
        """Obtain list of rules that became used since last call to this method (or since start of coverage instrumentation)"""
        return cast(
            "TakeCoverageDeltaReturns",
            await self._client.send_raw(
                method="CSS.takeCoverageDelta",
                params=params,
                session_id=session_id,
            ),
        )

    async def stopRuleUsageTracking(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "StopRuleUsageTrackingReturns":
        """The list of rules with an indication of whether these were used"""
        return cast(
            "StopRuleUsageTrackingReturns",
            await self._client.send_raw(
                method="CSS.stopRuleUsageTracking",
                params=params,
                session_id=session_id,
            ),
        )
