# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP CSS Domain Types"""

from typing import List
from typing_extensions import Literal
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import BackendNodeId
    from ..dom.types import PseudoType
    from ..page.types import FrameId

StyleSheetId = str


StyleSheetOrigin = Literal["injected", "user-agent", "inspector", "regular"]
"""Stylesheet type: "injected" for stylesheets injected via extension, "user-agent" for user-agent stylesheets, "inspector" for stylesheets created by the inspector (i.e. those holding the "via inspector" rules), "regular" for regular stylesheets."""


class PseudoElementMatches(TypedDict):
    """CSS rule collection for a single pseudo style."""

    pseudoType: "PseudoType"
    """Pseudo element type."""
    matches: "List[RuleMatch]"
    """Matches of CSS rules applicable to the pseudo style."""


class InheritedStyleEntry(TypedDict):
    """Inherited CSS rule collection from ancestor node."""

    inlineStyle: "NotRequired[CSSStyle]"
    """The ancestor node's inline style, if any, in the style inheritance chain."""
    matchedCSSRules: "List[RuleMatch]"
    """Matches of CSS rules matching the ancestor node in the style inheritance chain."""


class RuleMatch(TypedDict):
    """Match data for a CSS rule."""

    rule: "CSSRule"
    """CSS rule in the match."""
    matchingSelectors: "List[int]"
    """Matching selector indices in the rule's selectorList selectors (0-based)."""


class Value(TypedDict):
    """Data for a simple selector (these are delimited by commas in a selector list)."""

    text: "str"
    """Value text."""
    range: "NotRequired[SourceRange]"
    """Value range in the underlying resource (if available)."""


class SelectorList(TypedDict):
    """Selector list data."""

    selectors: "List[Value]"
    """Selectors in the list."""
    text: "str"
    """Rule selector text."""


class CSSStyleSheetHeader(TypedDict):
    """CSS stylesheet metainformation."""

    styleSheetId: "StyleSheetId"
    """The stylesheet identifier."""
    frameId: "FrameId"
    """Owner frame identifier."""
    sourceURL: "str"
    """Stylesheet resource URL."""
    sourceMapURL: "NotRequired[str]"
    """URL of source map associated with the stylesheet (if any)."""
    origin: "StyleSheetOrigin"
    """Stylesheet origin."""
    title: "str"
    """Stylesheet title."""
    ownerNode: "NotRequired[BackendNodeId]"
    """The backend id for the owner node of the stylesheet."""
    disabled: "bool"
    """Denotes whether the stylesheet is disabled."""
    hasSourceURL: "NotRequired[bool]"
    """Whether the sourceURL field value comes from the sourceURL comment."""
    isInline: "bool"
    """Whether this stylesheet is created for STYLE tag by parser. This flag is not set for document.written STYLE tags."""
    startLine: "float"
    """Line offset of the stylesheet within the resource (zero based)."""
    startColumn: "float"
    """Column offset of the stylesheet within the resource (zero based)."""
    length: "float"
    """Size of the content (in characters)."""


class CSSRule(TypedDict):
    """CSS rule representation."""

    styleSheetId: "NotRequired[StyleSheetId]"
    """The css style sheet identifier (absent for user agent stylesheet and user-specified stylesheet rules) this rule came from."""
    selectorList: "SelectorList"
    """Rule selector data."""
    origin: "StyleSheetOrigin"
    """Parent stylesheet's origin."""
    style: "CSSStyle"
    """Associated style declaration."""
    media: "NotRequired[List[CSSMedia]]"
    """Media list array (for rules involving media queries). The array enumerates media queries starting with the innermost one, going outwards."""


class RuleUsage(TypedDict):
    """CSS coverage information."""

    styleSheetId: "StyleSheetId"
    """The css style sheet identifier (absent for user agent stylesheet and user-specified stylesheet rules) this rule came from."""
    startOffset: "float"
    """Offset of the start of the rule (including selector) from the beginning of the stylesheet."""
    endOffset: "float"
    """Offset of the end of the rule body from the beginning of the stylesheet."""
    used: "bool"
    """Indicates whether the rule was actually used by some element in the page."""


class SourceRange(TypedDict):
    """Text range within a resource. All numbers are zero-based."""

    startLine: "int"
    """Start line of range."""
    startColumn: "int"
    """Start column of range (inclusive)."""
    endLine: "int"
    """End line of range"""
    endColumn: "int"
    """End column of range (exclusive)."""


class ShorthandEntry(TypedDict):
    name: "str"
    """Shorthand name."""
    value: "str"
    """Shorthand value."""
    important: "NotRequired[bool]"
    """Whether the property has \"!important\" annotation (implies <code>false</code> if absent)."""


class CSSComputedStyleProperty(TypedDict):
    name: "str"
    """Computed style property name."""
    value: "str"
    """Computed style property value."""


class CSSStyle(TypedDict):
    """CSS style representation."""

    styleSheetId: "NotRequired[StyleSheetId]"
    """The css style sheet identifier (absent for user agent stylesheet and user-specified stylesheet rules) this rule came from."""
    cssProperties: "List[CSSProperty]"
    """CSS properties in the style."""
    shorthandEntries: "List[ShorthandEntry]"
    """Computed values for all shorthands found in the style."""
    cssText: "NotRequired[str]"
    """Style declaration text (if available)."""
    range: "NotRequired[SourceRange]"
    """Style declaration range in the enclosing stylesheet (if available)."""


class CSSProperty(TypedDict):
    """CSS property declaration data."""

    name: "str"
    """The property name."""
    value: "str"
    """The property value."""
    important: "NotRequired[bool]"
    """Whether the property has \"!important\" annotation (implies <code>false</code> if absent)."""
    implicit: "NotRequired[bool]"
    """Whether the property is implicit (implies <code>false</code> if absent)."""
    text: "NotRequired[str]"
    """The full property text as specified in the style."""
    parsedOk: "NotRequired[bool]"
    """Whether the property is understood by the browser (implies <code>true</code> if absent)."""
    disabled: "NotRequired[bool]"
    """Whether the property is disabled by the user (present for source-based properties only)."""
    range: "NotRequired[SourceRange]"
    """The entire property range in the enclosing style declaration (if available)."""


class CSSMedia(TypedDict):
    """CSS media rule descriptor."""

    text: "str"
    """Media query text."""
    source: "str"
    """Source of the media query: \"mediaRule\" if specified by a @media rule, \"importRule\" if specified by an @import rule, \"linkedSheet\" if specified by a \"media\" attribute in a linked stylesheet's LINK tag, \"inlineSheet\" if specified by a \"media\" attribute in an inline stylesheet's STYLE tag."""
    sourceURL: "NotRequired[str]"
    """URL of the document containing the media query description."""
    range: "NotRequired[SourceRange]"
    """The associated rule (@media or @import) header range in the enclosing stylesheet (if available)."""
    styleSheetId: "NotRequired[StyleSheetId]"
    """Identifier of the stylesheet containing this object (if exists)."""
    mediaList: "NotRequired[List[MediaQuery]]"
    """Array of media queries."""


class MediaQuery(TypedDict):
    """Media query descriptor."""

    expressions: "List[MediaQueryExpression]"
    """Array of media query expressions."""
    active: "bool"
    """Whether the media query condition is satisfied."""


class MediaQueryExpression(TypedDict):
    """Media query expression descriptor."""

    value: "float"
    """Media query expression value."""
    unit: "str"
    """Media query expression units."""
    feature: "str"
    """Media query expression feature."""
    valueRange: "NotRequired[SourceRange]"
    """The associated range of the value text in the enclosing stylesheet (if available)."""
    computedLength: "NotRequired[float]"
    """Computed length of media query expression (if applicable)."""


class PlatformFontUsage(TypedDict):
    """Information about amount of glyphs that were rendered with given font."""

    familyName: "str"
    """Font's family name reported by platform."""
    isCustomFont: "bool"
    """Indicates if the font was downloaded or resolved locally."""
    glyphCount: "float"
    """Amount of glyphs that were rendered with this font."""


class CSSKeyframesRule(TypedDict):
    """CSS keyframes rule representation."""

    animationName: "Value"
    """Animation name."""
    keyframes: "List[CSSKeyframeRule]"
    """List of keyframes."""


class CSSKeyframeRule(TypedDict):
    """CSS keyframe rule representation."""

    styleSheetId: "NotRequired[StyleSheetId]"
    """The css style sheet identifier (absent for user agent stylesheet and user-specified stylesheet rules) this rule came from."""
    origin: "StyleSheetOrigin"
    """Parent stylesheet's origin."""
    keyText: "Value"
    """Associated key text."""
    style: "CSSStyle"
    """Associated style declaration."""


class StyleDeclarationEdit(TypedDict):
    """A descriptor of operation to mutate style declaration text."""

    styleSheetId: "StyleSheetId"
    """The css style sheet identifier."""
    range: "SourceRange"
    """The range of the style text in the enclosing stylesheet."""
    text: "str"
    """New style text."""
