# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Type-Safe Client"""

from . import schema
from . import runtime
from . import debugger
from . import console
from . import profiler
from . import heapprofiler
from . import inspector
from . import memory
from . import performance
from . import page
from . import overlay
from . import emulation
from . import security
from . import audits
from . import network
from . import database
from . import indexeddb
from . import cachestorage
from . import domstorage
from . import applicationcache
from . import dom
from . import css
from . import domsnapshot
from . import io
from . import domdebugger
from . import target
from . import headlessexperimental
from . import serviceworker
from . import input
from . import layertree
from . import deviceorientation
from . import tracing
from . import animation
from . import accessibility
from . import storage
from . import log
from . import systeminfo
from . import tethering
from . import browser
from . import browseruse

from .library import CDPLibrary
from .registry import EventRegistry
from .registration_library import CDPRegistrationLibrary

__all__ = [
    "schema",
    "runtime",
    "debugger",
    "console",
    "profiler",
    "heapprofiler",
    "inspector",
    "memory",
    "performance",
    "page",
    "overlay",
    "emulation",
    "security",
    "audits",
    "network",
    "database",
    "indexeddb",
    "cachestorage",
    "domstorage",
    "applicationcache",
    "dom",
    "css",
    "domsnapshot",
    "io",
    "domdebugger",
    "target",
    "headlessexperimental",
    "serviceworker",
    "input",
    "layertree",
    "deviceorientation",
    "tracing",
    "animation",
    "accessibility",
    "storage",
    "log",
    "systeminfo",
    "tethering",
    "browser",
    "browseruse",
    "CDPLibrary",
    "EventRegistry",
    "CDPRegistrationLibrary",
]
