# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Event Registration Library"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .registry import EventRegistry


class CDPRegistrationLibrary:
    """Main CDP registration library with domain-specific registration interfaces."""

    def __init__(self, registry: "EventRegistry"):
        self._registry = registry

        # Runtime domain registration
        from .runtime.registration import RuntimeRegistration

        self.Runtime = RuntimeRegistration(registry)

        # Debugger domain registration
        from .debugger.registration import DebuggerRegistration

        self.Debugger = DebuggerRegistration(registry)

        # Console domain registration
        from .console.registration import ConsoleRegistration

        self.Console = ConsoleRegistration(registry)

        # Profiler domain registration
        from .profiler.registration import ProfilerRegistration

        self.Profiler = ProfilerRegistration(registry)

        # HeapProfiler domain registration
        from .heapprofiler.registration import HeapProfilerRegistration

        self.HeapProfiler = HeapProfilerRegistration(registry)

        # Inspector domain registration
        from .inspector.registration import InspectorRegistration

        self.Inspector = InspectorRegistration(registry)

        # Performance domain registration
        from .performance.registration import PerformanceRegistration

        self.Performance = PerformanceRegistration(registry)

        # Page domain registration
        from .page.registration import PageRegistration

        self.Page = PageRegistration(registry)

        # Overlay domain registration
        from .overlay.registration import OverlayRegistration

        self.Overlay = OverlayRegistration(registry)

        # Emulation domain registration
        from .emulation.registration import EmulationRegistration

        self.Emulation = EmulationRegistration(registry)

        # Security domain registration
        from .security.registration import SecurityRegistration

        self.Security = SecurityRegistration(registry)

        # Network domain registration
        from .network.registration import NetworkRegistration

        self.Network = NetworkRegistration(registry)

        # Database domain registration
        from .database.registration import DatabaseRegistration

        self.Database = DatabaseRegistration(registry)

        # DOMStorage domain registration
        from .domstorage.registration import DOMStorageRegistration

        self.DOMStorage = DOMStorageRegistration(registry)

        # ApplicationCache domain registration
        from .applicationcache.registration import ApplicationCacheRegistration

        self.ApplicationCache = ApplicationCacheRegistration(registry)

        # DOM domain registration
        from .dom.registration import DOMRegistration

        self.DOM = DOMRegistration(registry)

        # CSS domain registration
        from .css.registration import CSSRegistration

        self.CSS = CSSRegistration(registry)

        # Target domain registration
        from .target.registration import TargetRegistration

        self.Target = TargetRegistration(registry)

        # HeadlessExperimental domain registration
        from .headlessexperimental.registration import HeadlessExperimentalRegistration

        self.HeadlessExperimental = HeadlessExperimentalRegistration(registry)

        # ServiceWorker domain registration
        from .serviceworker.registration import ServiceWorkerRegistration

        self.ServiceWorker = ServiceWorkerRegistration(registry)

        # LayerTree domain registration
        from .layertree.registration import LayerTreeRegistration

        self.LayerTree = LayerTreeRegistration(registry)

        # Tracing domain registration
        from .tracing.registration import TracingRegistration

        self.Tracing = TracingRegistration(registry)

        # Animation domain registration
        from .animation.registration import AnimationRegistration

        self.Animation = AnimationRegistration(registry)

        # Storage domain registration
        from .storage.registration import StorageRegistration

        self.Storage = StorageRegistration(registry)

        # Log domain registration
        from .log.registration import LogRegistration

        self.Log = LogRegistration(registry)

        # Tethering domain registration
        from .tethering.registration import TetheringRegistration

        self.Tethering = TetheringRegistration(registry)

        # BrowserUse domain registration
        from .browseruse.registration import BrowserUseRegistration

        self.BrowserUse = BrowserUseRegistration(registry)
