# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP HeapProfiler Domain Commands"""

from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..runtime.types import RemoteObject
    from ..runtime.types import RemoteObjectId
    from .types import HeapSnapshotObjectId
    from .types import SamplingHeapProfile


class StartTrackingHeapObjectsParameters(TypedDict, total=False):
    trackAllocations: "bool"


class StopTrackingHeapObjectsParameters(TypedDict, total=False):
    reportProgress: "bool"
    """If true 'reportHeapSnapshotProgress' events will be generated while snapshot is being taken when the tracking is stopped."""


class TakeHeapSnapshotParameters(TypedDict, total=False):
    reportProgress: "bool"
    """If true 'reportHeapSnapshotProgress' events will be generated while snapshot is being taken."""


class GetObjectByHeapObjectIdParameters(TypedDict):
    objectId: "HeapSnapshotObjectId"
    objectGroup: "NotRequired[str]"
    """Symbolic group name that can be used to release multiple objects."""


class GetObjectByHeapObjectIdReturns(TypedDict):
    result: "RemoteObject"
    """Evaluation result."""


class AddInspectedHeapObjectParameters(TypedDict):
    heapObjectId: "HeapSnapshotObjectId"
    """Heap snapshot object id to be accessible by means of $x command line API."""


class GetHeapObjectIdParameters(TypedDict):
    objectId: "RemoteObjectId"
    """Identifier of the object to get heap object id for."""


class GetHeapObjectIdReturns(TypedDict):
    heapSnapshotObjectId: "HeapSnapshotObjectId"
    """Id of the heap snapshot object corresponding to the passed remote object id."""


class StartSamplingParameters(TypedDict, total=False):
    samplingInterval: "float"
    """Average sample interval in bytes. Poisson distribution is used for the intervals. The default value is 32768 bytes."""


class StopSamplingReturns(TypedDict):
    profile: "SamplingHeapProfile"
    """Recorded sampling heap profile."""


class GetSamplingProfileReturns(TypedDict):
    profile: "SamplingHeapProfile"
    """Return the sampling profile being collected."""
