# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP HeapProfiler Domain Types"""

from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..runtime.types import CallFrame

HeapSnapshotObjectId = str
"""Heap snapshot object id."""


class SamplingHeapProfileNode(TypedDict):
    """Sampling Heap Profile node. Holds callsite information, allocation statistics and child nodes."""

    callFrame: "CallFrame"
    """Function location."""
    selfSize: "float"
    """Allocations size in bytes for the node excluding children."""
    children: "List[SamplingHeapProfileNode]"
    """Child nodes."""


class SamplingHeapProfile(TypedDict):
    """Profile."""

    head: "SamplingHeapProfileNode"
