# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Emulation Domain Commands"""

from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import RGBA
    from ..page.types import Viewport
    from ..runtime.types import Timestamp
    from .types import ScreenOrientation
    from .types import VirtualTimePolicy


class SetDeviceMetricsOverrideParameters(TypedDict):
    width: "int"
    """Overriding width value in pixels (minimum 0, maximum 10000000). 0 disables the override."""
    height: "int"
    """Overriding height value in pixels (minimum 0, maximum 10000000). 0 disables the override."""
    deviceScaleFactor: "float"
    """Overriding device scale factor value. 0 disables the override."""
    mobile: "bool"
    """Whether to emulate mobile device. This includes viewport meta tag, overlay scrollbars, text autosizing and more."""
    scale: "NotRequired[float]"
    """Scale to apply to resulting view image."""
    screenWidth: "NotRequired[int]"
    """Overriding screen width value in pixels (minimum 0, maximum 10000000)."""
    screenHeight: "NotRequired[int]"
    """Overriding screen height value in pixels (minimum 0, maximum 10000000)."""
    positionX: "NotRequired[int]"
    """Overriding view X position on screen in pixels (minimum 0, maximum 10000000)."""
    positionY: "NotRequired[int]"
    """Overriding view Y position on screen in pixels (minimum 0, maximum 10000000)."""
    dontSetVisibleSize: "NotRequired[bool]"
    """Do not set visible view size, rely upon explicit setVisibleSize call."""
    screenOrientation: "NotRequired[ScreenOrientation]"
    """Screen orientation override."""
    viewport: "NotRequired[Viewport]"
    """If set, the visible area of the page will be overridden to this viewport. This viewport change is not observed by the page, e.g. viewport-relative elements do not change positions."""


class SetPageScaleFactorParameters(TypedDict):
    pageScaleFactor: "float"
    """Page scale factor."""


class SetVisibleSizeParameters(TypedDict):
    width: "int"
    """Frame width (DIP)."""
    height: "int"
    """Frame height (DIP)."""


class SetScriptExecutionDisabledParameters(TypedDict):
    value: "bool"
    """Whether script execution should be disabled in the page."""


class SetGeolocationOverrideParameters(TypedDict, total=False):
    latitude: "float"
    """Mock latitude"""
    longitude: "float"
    """Mock longitude"""
    accuracy: "float"
    """Mock accuracy"""


class SetTouchEmulationEnabledParameters(TypedDict):
    enabled: "bool"
    """Whether the touch event emulation should be enabled."""
    maxTouchPoints: "NotRequired[int]"
    """Maximum touch points supported. Defaults to one."""


class SetEmitTouchEventsForMouseParameters(TypedDict):
    enabled: "bool"
    """Whether touch emulation based on mouse input should be enabled."""
    configuration: "NotRequired[str]"
    """Touch/gesture events configuration. Default: current platform."""


class SetEmulatedMediaParameters(TypedDict):
    media: "str"
    """Media type to emulate. Empty string disables the override."""


class SetCPUThrottlingRateParameters(TypedDict):
    rate: "float"
    """Throttling rate as a slowdown factor (1 is no throttle, 2 is 2x slowdown, etc)."""


class CanEmulateReturns(TypedDict):
    result: "bool"
    """True if emulation is supported."""


class SetVirtualTimePolicyParameters(TypedDict):
    policy: "VirtualTimePolicy"
    budget: "NotRequired[float]"
    """If set, after this many virtual milliseconds have elapsed virtual time will be paused and a virtualTimeBudgetExpired event is sent."""
    maxVirtualTimeTaskStarvationCount: "NotRequired[int]"
    """If set this specifies the maximum number of tasks that can be run before virtual is forced forwards to prevent deadlock."""


class SetVirtualTimePolicyReturns(TypedDict):
    virtualTimeBase: "Timestamp"
    """Absolute timestamp at which virtual time was first enabled (milliseconds since epoch)."""


class SetNavigatorOverridesParameters(TypedDict):
    platform: "str"
    """The platform navigator.platform should return."""


class SetDefaultBackgroundColorOverrideParameters(TypedDict, total=False):
    color: "RGBA"
    """RGBA of the default background color. If not specified, any existing override will be cleared."""
