# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Emulation Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import CanEmulateReturns
    from .commands import SetCPUThrottlingRateParameters
    from .commands import SetDefaultBackgroundColorOverrideParameters
    from .commands import SetDeviceMetricsOverrideParameters
    from .commands import SetEmitTouchEventsForMouseParameters
    from .commands import SetEmulatedMediaParameters
    from .commands import SetGeolocationOverrideParameters
    from .commands import SetNavigatorOverridesParameters
    from .commands import SetPageScaleFactorParameters
    from .commands import SetScriptExecutionDisabledParameters
    from .commands import SetTouchEmulationEnabledParameters
    from .commands import SetVirtualTimePolicyParameters
    from .commands import SetVirtualTimePolicyReturns
    from .commands import SetVisibleSizeParameters


class EmulationClient:
    """Client for Emulation domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def setDeviceMetricsOverride(
        self,
        params: "SetDeviceMetricsOverrideParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Overrides the values of device screen dimensions (window.screen.width, window.screen.height, window.innerWidth, window.innerHeight, and \"device-width\"/\"device-height\"-related CSS media query results)."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setDeviceMetricsOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def clearDeviceMetricsOverride(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Clears the overriden device metrics."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.clearDeviceMetricsOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def resetPageScaleFactor(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Requests that page scale factor is reset to initial values."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.resetPageScaleFactor",
                params=params,
                session_id=session_id,
            ),
        )

    async def setPageScaleFactor(
        self,
        params: "SetPageScaleFactorParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Sets a specified page scale factor."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setPageScaleFactor",
                params=params,
                session_id=session_id,
            ),
        )

    async def setVisibleSize(
        self,
        params: "SetVisibleSizeParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Resizes the frame/viewport of the page. Note that this does not affect the frame's container (e.g. browser window). Can be used to produce screenshots of the specified size. Not supported on Android."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setVisibleSize",
                params=params,
                session_id=session_id,
            ),
        )

    async def setScriptExecutionDisabled(
        self,
        params: "SetScriptExecutionDisabledParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Switches script execution in the page."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setScriptExecutionDisabled",
                params=params,
                session_id=session_id,
            ),
        )

    async def setGeolocationOverride(
        self,
        params: Optional["SetGeolocationOverrideParameters"] = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Overrides the Geolocation Position or Error. Omitting any of the parameters emulates position unavailable."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setGeolocationOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def clearGeolocationOverride(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Clears the overriden Geolocation Position and Error."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.clearGeolocationOverride",
                params=params,
                session_id=session_id,
            ),
        )

    async def setTouchEmulationEnabled(
        self,
        params: "SetTouchEmulationEnabledParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enables touch on platforms which do not support them."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setTouchEmulationEnabled",
                params=params,
                session_id=session_id,
            ),
        )

    async def setEmitTouchEventsForMouse(
        self,
        params: "SetEmitTouchEventsForMouseParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setEmitTouchEventsForMouse",
                params=params,
                session_id=session_id,
            ),
        )

    async def setEmulatedMedia(
        self,
        params: "SetEmulatedMediaParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Emulates the given media for CSS media queries."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setEmulatedMedia",
                params=params,
                session_id=session_id,
            ),
        )

    async def setCPUThrottlingRate(
        self,
        params: "SetCPUThrottlingRateParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enables CPU throttling to emulate slow CPUs."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setCPUThrottlingRate",
                params=params,
                session_id=session_id,
            ),
        )

    async def canEmulate(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "CanEmulateReturns":
        """Tells whether emulation is supported."""
        return cast(
            "CanEmulateReturns",
            await self._client.send_raw(
                method="Emulation.canEmulate",
                params=params,
                session_id=session_id,
            ),
        )

    async def setVirtualTimePolicy(
        self,
        params: "SetVirtualTimePolicyParameters",
        session_id: Optional[str] = None,
    ) -> "SetVirtualTimePolicyReturns":
        """Turns on virtual time for all frames (replacing real-time with a synthetic time source) and sets the current virtual time policy.  Note this supersedes any previous time budget."""
        return cast(
            "SetVirtualTimePolicyReturns",
            await self._client.send_raw(
                method="Emulation.setVirtualTimePolicy",
                params=params,
                session_id=session_id,
            ),
        )

    async def setNavigatorOverrides(
        self,
        params: "SetNavigatorOverridesParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Overrides value returned by the javascript navigator object."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setNavigatorOverrides",
                params=params,
                session_id=session_id,
            ),
        )

    async def setDefaultBackgroundColorOverride(
        self,
        params: Optional["SetDefaultBackgroundColorOverrideParameters"] = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Sets or clears an override of the default background color of the frame. This override is used if the content does not specify one."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Emulation.setDefaultBackgroundColorOverride",
                params=params,
                session_id=session_id,
            ),
        )
