# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Emulation Domain Types"""

from typing_extensions import Literal
from typing_extensions import TypedDict


class ScreenOrientation(TypedDict):
    """Screen orientation."""

    type: "str"
    """Orientation type."""
    angle: "int"
    """Orientation angle."""


VirtualTimePolicy = Literal["advance", "pause", "pauseIfNetworkFetchesPending"]
"""advance: If the scheduler runs out of immediate work, the virtual time base may fast forward to allow the next delayed task (if any) to run; pause: The virtual time base may not advance; pauseIfNetworkFetchesPending: The virtual time base may not advance if there are any pending resource fetches."""
