# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Debugger Domain Commands"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..runtime.types import CallArgument
    from ..runtime.types import ExceptionDetails
    from ..runtime.types import RemoteObject
    from ..runtime.types import ScriptId
    from ..runtime.types import StackTrace
    from ..runtime.types import StackTraceId
    from ..runtime.types import UniqueDebuggerId
    from .types import BreakLocation
    from .types import BreakpointId
    from .types import CallFrame
    from .types import CallFrameId
    from .types import Location
    from .types import ScriptPosition
    from .types import SearchMatch


class EnableReturns(TypedDict):
    debuggerId: "UniqueDebuggerId"
    """Unique identifier of the debugger."""


class SetBreakpointsActiveParameters(TypedDict):
    active: "bool"
    """New value for breakpoints active state."""


class SetSkipAllPausesParameters(TypedDict):
    skip: "bool"
    """New value for skip pauses state."""


class SetBreakpointByUrlParameters(TypedDict):
    lineNumber: "int"
    """Line number to set breakpoint at."""
    url: "NotRequired[str]"
    """URL of the resources to set breakpoint on."""
    urlRegex: "NotRequired[str]"
    """Regex pattern for the URLs of the resources to set breakpoints on. Either <code>url</code> or <code>urlRegex</code> must be specified."""
    scriptHash: "NotRequired[str]"
    """Script hash of the resources to set breakpoint on."""
    columnNumber: "NotRequired[int]"
    """Offset in the line to set breakpoint at."""
    condition: "NotRequired[str]"
    """Expression to use as a breakpoint condition. When specified, debugger will only stop on the breakpoint if this expression evaluates to true."""


class SetBreakpointByUrlReturns(TypedDict):
    breakpointId: "BreakpointId"
    """Id of the created breakpoint for further reference."""
    locations: "List[Location]"
    """List of the locations this breakpoint resolved into upon addition."""


class SetBreakpointParameters(TypedDict):
    location: "Location"
    """Location to set breakpoint in."""
    condition: "NotRequired[str]"
    """Expression to use as a breakpoint condition. When specified, debugger will only stop on the breakpoint if this expression evaluates to true."""


class SetBreakpointReturns(TypedDict):
    breakpointId: "BreakpointId"
    """Id of the created breakpoint for further reference."""
    actualLocation: "Location"
    """Location this breakpoint resolved into."""


class RemoveBreakpointParameters(TypedDict):
    breakpointId: "BreakpointId"


class GetPossibleBreakpointsParameters(TypedDict):
    start: "Location"
    """Start of range to search possible breakpoint locations in."""
    end: "NotRequired[Location]"
    """End of range to search possible breakpoint locations in (excluding). When not specified, end of scripts is used as end of range."""
    restrictToFunction: "NotRequired[bool]"
    """Only consider locations which are in the same (non-nested) function as start."""


class GetPossibleBreakpointsReturns(TypedDict):
    locations: "List[BreakLocation]"
    """List of the possible breakpoint locations."""


class ContinueToLocationParameters(TypedDict):
    location: "Location"
    """Location to continue to."""
    targetCallFrames: "NotRequired[str]"


class PauseOnAsyncCallParameters(TypedDict):
    parentStackTraceId: "StackTraceId"
    """Debugger will pause when async call with given stack trace is started."""


class StepIntoParameters(TypedDict, total=False):
    breakOnAsyncCall: "bool"
    """Debugger will issue additional Debugger.paused notification if any async task is scheduled before next pause."""


class GetStackTraceParameters(TypedDict):
    stackTraceId: "StackTraceId"


class GetStackTraceReturns(TypedDict):
    stackTrace: "StackTrace"


class SearchInContentParameters(TypedDict):
    scriptId: "ScriptId"
    """Id of the script to search in."""
    query: "str"
    """String to search for."""
    caseSensitive: "NotRequired[bool]"
    """If true, search is case sensitive."""
    isRegex: "NotRequired[bool]"
    """If true, treats string parameter as regex."""


class SearchInContentReturns(TypedDict):
    result: "List[SearchMatch]"
    """List of search matches."""


class SetScriptSourceParameters(TypedDict):
    scriptId: "ScriptId"
    """Id of the script to edit."""
    scriptSource: "str"
    """New content of the script."""
    dryRun: "NotRequired[bool]"
    """ If true the change will not actually be applied. Dry run may be used to get result description without actually modifying the code."""


class SetScriptSourceReturns(TypedDict):
    callFrames: "List[CallFrame]"
    """New stack trace in case editing has happened while VM was stopped."""
    stackChanged: "bool"
    """Whether current call stack  was modified after applying the changes."""
    asyncStackTrace: "StackTrace"
    """Async stack trace, if any."""
    asyncStackTraceId: "StackTraceId"
    """Async stack trace, if any."""
    exceptionDetails: "ExceptionDetails"
    """Exception details if any."""


class RestartFrameParameters(TypedDict):
    callFrameId: "CallFrameId"
    """Call frame identifier to evaluate on."""


class RestartFrameReturns(TypedDict):
    callFrames: "List[CallFrame]"
    """New stack trace."""
    asyncStackTrace: "StackTrace"
    """Async stack trace, if any."""
    asyncStackTraceId: "StackTraceId"
    """Async stack trace, if any."""


class GetScriptSourceParameters(TypedDict):
    scriptId: "ScriptId"
    """Id of the script to get source for."""


class GetScriptSourceReturns(TypedDict):
    scriptSource: "str"
    """Script source."""


class SetPauseOnExceptionsParameters(TypedDict):
    state: "str"
    """Pause on exceptions mode."""


class EvaluateOnCallFrameParameters(TypedDict):
    callFrameId: "CallFrameId"
    """Call frame identifier to evaluate on."""
    expression: "str"
    """Expression to evaluate."""
    objectGroup: "NotRequired[str]"
    """String object group name to put result into (allows rapid releasing resulting object handles using <code>releaseObjectGroup</code>)."""
    includeCommandLineAPI: "NotRequired[bool]"
    """Specifies whether command line API should be available to the evaluated expression, defaults to false."""
    silent: "NotRequired[bool]"
    """In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides <code>setPauseOnException</code> state."""
    returnByValue: "NotRequired[bool]"
    """Whether the result is expected to be a JSON object that should be sent by value."""
    generatePreview: "NotRequired[bool]"
    """Whether preview should be generated for the result."""
    throwOnSideEffect: "NotRequired[bool]"
    """Whether to throw an exception if side effect cannot be ruled out during evaluation."""


class EvaluateOnCallFrameReturns(TypedDict):
    result: "RemoteObject"
    """Object wrapper for the evaluation result."""
    exceptionDetails: "ExceptionDetails"
    """Exception details."""


class SetVariableValueParameters(TypedDict):
    scopeNumber: "int"
    """0-based number of scope as was listed in scope chain. Only 'local', 'closure' and 'catch' scope types are allowed. Other scopes could be manipulated manually."""
    variableName: "str"
    """Variable name."""
    newValue: "CallArgument"
    """New variable value."""
    callFrameId: "CallFrameId"
    """Id of callframe that holds variable."""


class SetReturnValueParameters(TypedDict):
    newValue: "CallArgument"
    """New return value."""


class SetAsyncCallStackDepthParameters(TypedDict):
    maxDepth: "int"
    """Maximum depth of async call stacks. Setting to <code>0</code> will effectively disable collecting async call stacks (default)."""


class SetBlackboxPatternsParameters(TypedDict):
    patterns: "List[str]"
    """Array of regexps that will be used to check script url for blackbox state."""


class SetBlackboxedRangesParameters(TypedDict):
    scriptId: "ScriptId"
    """Id of the script."""
    positions: "List[ScriptPosition]"
