# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Debugger Domain Types"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..runtime.types import RemoteObject
    from ..runtime.types import ScriptId

BreakpointId = str
"""Breakpoint identifier."""


CallFrameId = str
"""Call frame identifier."""


class Location(TypedDict):
    """Location in the source code."""

    scriptId: "ScriptId"
    """Script identifier as reported in the <code>Debugger.scriptParsed</code>."""
    lineNumber: "int"
    """Line number in the script (0-based)."""
    columnNumber: "NotRequired[int]"
    """Column number in the script (0-based)."""


class ScriptPosition(TypedDict):
    """Location in the source code."""

    lineNumber: "int"
    columnNumber: "int"


class CallFrame(TypedDict):
    """JavaScript call frame. Array of call frames form the call stack."""

    callFrameId: "CallFrameId"
    """Call frame identifier. This identifier is only valid while the virtual machine is paused."""
    functionName: "str"
    """Name of the JavaScript function called on this call frame."""
    functionLocation: "NotRequired[Location]"
    """Location in the source code."""
    location: "Location"
    """Location in the source code."""
    url: "str"
    """JavaScript script name or url."""
    scopeChain: "List[Scope]"
    """Scope chain for this call frame."""
    this: "RemoteObject"
    """<code>this</code> object for this call frame."""
    returnValue: "NotRequired[RemoteObject]"
    """The value being returned, if the function is at return point."""


class Scope(TypedDict):
    """Scope description."""

    type: "str"
    """Scope type."""
    object: "RemoteObject"
    """Object representing the scope. For <code>global</code> and <code>with</code> scopes it represents the actual object; for the rest of the scopes, it is artificial transient object enumerating scope variables as its properties."""
    name: "NotRequired[str]"
    startLocation: "NotRequired[Location]"
    """Location in the source code where scope starts"""
    endLocation: "NotRequired[Location]"
    """Location in the source code where scope ends"""


class SearchMatch(TypedDict):
    """Search match for resource."""

    lineNumber: "float"
    """Line number in resource content."""
    lineContent: "str"
    """Line with match content."""


class BreakLocation(TypedDict):
    scriptId: "ScriptId"
    """Script identifier as reported in the <code>Debugger.scriptParsed</code>."""
    lineNumber: "int"
    """Line number in the script (0-based)."""
    columnNumber: "NotRequired[int]"
    """Column number in the script (0-based)."""
    type: "NotRequired[str]"
