# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Security Domain Types"""

from typing import List
from typing_extensions import Literal
from typing_extensions import TypedDict

CertificateId = int
"""An internal certificate ID value."""


MixedContentType = Literal["blockable", "optionally-blockable", "none"]
"""A description of mixed content (HTTP resources on HTTPS pages), as defined by https://www.w3.org/TR/mixed-content/#categories"""


SecurityState = Literal["unknown", "neutral", "insecure", "secure", "info"]
"""The security level of a page or resource."""


class SecurityStateExplanation(TypedDict):
    """An explanation of an factor contributing to the security state."""

    securityState: "SecurityState"
    """Security state representing the severity of the factor being explained."""
    summary: "str"
    """Short phrase describing the type of factor."""
    description: "str"
    """Full text explanation of the factor."""
    mixedContentType: "MixedContentType"
    """The type of mixed content described by the explanation."""
    certificate: "List[str]"
    """Page certificate."""


class InsecureContentStatus(TypedDict):
    """Information about insecure content on the page."""

    ranMixedContent: "bool"
    """True if the page was loaded over HTTPS and ran mixed (HTTP) content such as scripts."""
    displayedMixedContent: "bool"
    """True if the page was loaded over HTTPS and displayed mixed (HTTP) content such as images."""
    containedMixedForm: "bool"
    """True if the page was loaded over HTTPS and contained a form targeting an insecure url."""
    ranContentWithCertErrors: "bool"
    """True if the page was loaded over HTTPS without certificate errors, and ran content such as scripts that were loaded with certificate errors."""
    displayedContentWithCertErrors: "bool"
    """True if the page was loaded over HTTPS without certificate errors, and displayed content such as images that were loaded with certificate errors."""
    ranInsecureContentStyle: "SecurityState"
    """Security state representing a page that ran insecure content."""
    displayedInsecureContentStyle: "SecurityState"
    """Security state representing a page that displayed insecure content."""


CertificateErrorAction = Literal["continue", "cancel"]
"""The action to take when a certificate error occurs. continue will continue processing the request and cancel will cancel the request."""
