# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Memory Domain Commands"""

from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import PressureLevel


class GetDOMCountersReturns(TypedDict):
    documents: "int"
    nodes: "int"
    jsEventListeners: "int"


class SetPressureNotificationsSuppressedParameters(TypedDict):
    suppressed: "bool"
    """If true, memory pressure notifications will be suppressed."""


class SimulatePressureNotificationParameters(TypedDict):
    level: "PressureLevel"
    """Memory pressure level of the notification."""
