# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Memory Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import GetDOMCountersReturns
    from .commands import SetPressureNotificationsSuppressedParameters
    from .commands import SimulatePressureNotificationParameters


class MemoryClient:
    """Client for Memory domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def getDOMCounters(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetDOMCountersReturns":
        return cast(
            "GetDOMCountersReturns",
            await self._client.send_raw(
                method="Memory.getDOMCounters",
                params=params,
                session_id=session_id,
            ),
        )

    async def prepareForLeakDetection(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Memory.prepareForLeakDetection",
                params=params,
                session_id=session_id,
            ),
        )

    async def setPressureNotificationsSuppressed(
        self,
        params: "SetPressureNotificationsSuppressedParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enable/disable suppressing memory pressure notifications in all processes."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Memory.setPressureNotificationsSuppressed",
                params=params,
                session_id=session_id,
            ),
        )

    async def simulatePressureNotification(
        self,
        params: "SimulatePressureNotificationParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Simulate a memory pressure notification in all processes."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Memory.simulatePressureNotification",
                params=params,
                session_id=session_id,
            ),
        )
