# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Memory Domain Types"""

from typing_extensions import Literal

PressureLevel = Literal["moderate", "critical"]
"""Memory pressure level."""
