# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP IndexedDB Domain Commands"""

from typing import List
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import DataEntry
    from .types import DatabaseWithObjectStores
    from .types import KeyRange


class RequestDatabaseNamesParameters(TypedDict):
    securityOrigin: "str"
    """Security origin."""


class RequestDatabaseNamesReturns(TypedDict):
    databaseNames: "List[str]"
    """Database names for origin."""


class RequestDatabaseParameters(TypedDict):
    securityOrigin: "str"
    """Security origin."""
    databaseName: "str"
    """Database name."""


class RequestDatabaseReturns(TypedDict):
    databaseWithObjectStores: "DatabaseWithObjectStores"
    """Database with an array of object stores."""


class RequestDataParameters(TypedDict):
    securityOrigin: "str"
    """Security origin."""
    databaseName: "str"
    """Database name."""
    objectStoreName: "str"
    """Object store name."""
    indexName: "str"
    """Index name, empty string for object store data requests."""
    skipCount: "int"
    """Number of records to skip."""
    pageSize: "int"
    """Number of records to fetch."""
    keyRange: "NotRequired[KeyRange]"
    """Key range."""


class RequestDataReturns(TypedDict):
    objectStoreDataEntries: "List[DataEntry]"
    """Array of object store data entries."""
    hasMore: "bool"
    """If true, there are more entries to fetch in the given range."""


class ClearObjectStoreParameters(TypedDict):
    securityOrigin: "str"
    """Security origin."""
    databaseName: "str"
    """Database name."""
    objectStoreName: "str"
    """Object store name."""


class DeleteDatabaseParameters(TypedDict):
    securityOrigin: "str"
    """Security origin."""
    databaseName: "str"
    """Database name."""
