# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Overlay Domain Commands"""

from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import BackendNodeId
    from ..dom.types import NodeId
    from ..dom.types import Quad
    from ..dom.types import RGBA
    from ..page.types import FrameId
    from ..runtime.types import RemoteObjectId
    from .types import HighlightConfig
    from .types import InspectMode


class SetShowPaintRectsParameters(TypedDict):
    result: "bool"
    """True for showing paint rectangles"""


class SetShowDebugBordersParameters(TypedDict):
    show: "bool"
    """True for showing debug borders"""


class SetShowFPSCounterParameters(TypedDict):
    show: "bool"
    """True for showing the FPS counter"""


class SetShowScrollBottleneckRectsParameters(TypedDict):
    show: "bool"
    """True for showing scroll bottleneck rects"""


class SetShowViewportSizeOnResizeParameters(TypedDict):
    show: "bool"
    """Whether to paint size or not."""


class SetPausedInDebuggerMessageParameters(TypedDict, total=False):
    message: "str"
    """The message to display, also triggers resume and step over controls."""


class SetSuspendedParameters(TypedDict):
    suspended: "bool"
    """Whether overlay should be suspended and not consume any resources until resumed."""


class SetInspectModeParameters(TypedDict):
    mode: "InspectMode"
    """Set an inspection mode."""
    highlightConfig: "NotRequired[HighlightConfig]"
    """A descriptor for the highlight appearance of hovered-over nodes. May be omitted if <code>enabled == false</code>."""


class HighlightRectParameters(TypedDict):
    x: "int"
    """X coordinate"""
    y: "int"
    """Y coordinate"""
    width: "int"
    """Rectangle width"""
    height: "int"
    """Rectangle height"""
    color: "NotRequired[RGBA]"
    """The highlight fill color (default: transparent)."""
    outlineColor: "NotRequired[RGBA]"
    """The highlight outline color (default: transparent)."""


class HighlightQuadParameters(TypedDict):
    quad: "Quad"
    """Quad to highlight"""
    color: "NotRequired[RGBA]"
    """The highlight fill color (default: transparent)."""
    outlineColor: "NotRequired[RGBA]"
    """The highlight outline color (default: transparent)."""


class HighlightNodeParameters(TypedDict):
    highlightConfig: "HighlightConfig"
    """A descriptor for the highlight appearance."""
    nodeId: "NotRequired[NodeId]"
    """Identifier of the node to highlight."""
    backendNodeId: "NotRequired[BackendNodeId]"
    """Identifier of the backend node to highlight."""
    objectId: "NotRequired[RemoteObjectId]"
    """JavaScript object id of the node to be highlighted."""


class HighlightFrameParameters(TypedDict):
    frameId: "FrameId"
    """Identifier of the frame to highlight."""
    contentColor: "NotRequired[RGBA]"
    """The content box highlight fill color (default: transparent)."""
    contentOutlineColor: "NotRequired[RGBA]"
    """The content box highlight outline color (default: transparent)."""


class GetHighlightObjectForTestParameters(TypedDict):
    nodeId: "NodeId"
    """Id of the node to get highlight object for."""


class GetHighlightObjectForTestReturns(TypedDict):
    highlight: "Dict[str, Any]"
    """Highlight data for the node."""
