# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Overlay Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import GetHighlightObjectForTestParameters
    from .commands import GetHighlightObjectForTestReturns
    from .commands import HighlightFrameParameters
    from .commands import HighlightNodeParameters
    from .commands import HighlightQuadParameters
    from .commands import HighlightRectParameters
    from .commands import SetInspectModeParameters
    from .commands import SetPausedInDebuggerMessageParameters
    from .commands import SetShowDebugBordersParameters
    from .commands import SetShowFPSCounterParameters
    from .commands import SetShowPaintRectsParameters
    from .commands import SetShowScrollBottleneckRectsParameters
    from .commands import SetShowViewportSizeOnResizeParameters
    from .commands import SetSuspendedParameters


class OverlayClient:
    """Client for Overlay domain commands."""

    def __init__(self, client: "CDPClient"):
        self._client = client

    async def enable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enables domain notifications."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.enable",
                params=params,
                session_id=session_id,
            ),
        )

    async def disable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Disables domain notifications."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.disable",
                params=params,
                session_id=session_id,
            ),
        )

    async def setShowPaintRects(
        self,
        params: "SetShowPaintRectsParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Requests that backend shows paint rectangles"""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.setShowPaintRects",
                params=params,
                session_id=session_id,
            ),
        )

    async def setShowDebugBorders(
        self,
        params: "SetShowDebugBordersParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Requests that backend shows debug borders on layers"""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.setShowDebugBorders",
                params=params,
                session_id=session_id,
            ),
        )

    async def setShowFPSCounter(
        self,
        params: "SetShowFPSCounterParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Requests that backend shows the FPS counter"""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.setShowFPSCounter",
                params=params,
                session_id=session_id,
            ),
        )

    async def setShowScrollBottleneckRects(
        self,
        params: "SetShowScrollBottleneckRectsParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Requests that backend shows scroll bottleneck rects"""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.setShowScrollBottleneckRects",
                params=params,
                session_id=session_id,
            ),
        )

    async def setShowViewportSizeOnResize(
        self,
        params: "SetShowViewportSizeOnResizeParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Paints viewport size upon main frame resize."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.setShowViewportSizeOnResize",
                params=params,
                session_id=session_id,
            ),
        )

    async def setPausedInDebuggerMessage(
        self,
        params: Optional["SetPausedInDebuggerMessageParameters"] = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.setPausedInDebuggerMessage",
                params=params,
                session_id=session_id,
            ),
        )

    async def setSuspended(
        self,
        params: "SetSuspendedParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.setSuspended",
                params=params,
                session_id=session_id,
            ),
        )

    async def setInspectMode(
        self,
        params: "SetInspectModeParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Enters the 'inspect' mode. In this mode, elements that user is hovering over are highlighted. Backend then generates 'inspectNodeRequested' event upon element selection."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.setInspectMode",
                params=params,
                session_id=session_id,
            ),
        )

    async def highlightRect(
        self,
        params: "HighlightRectParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Highlights given rectangle. Coordinates are absolute with respect to the main frame viewport."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.highlightRect",
                params=params,
                session_id=session_id,
            ),
        )

    async def highlightQuad(
        self,
        params: "HighlightQuadParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Highlights given quad. Coordinates are absolute with respect to the main frame viewport."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.highlightQuad",
                params=params,
                session_id=session_id,
            ),
        )

    async def highlightNode(
        self,
        params: "HighlightNodeParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Highlights DOM node with given id or with the given JavaScript object wrapper. Either nodeId or objectId must be specified."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.highlightNode",
                params=params,
                session_id=session_id,
            ),
        )

    async def highlightFrame(
        self,
        params: "HighlightFrameParameters",
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Highlights owner element of the frame with given id."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.highlightFrame",
                params=params,
                session_id=session_id,
            ),
        )

    async def hideHighlight(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        """Hides any highlight."""
        return cast(
            "Dict[str, Any]",
            await self._client.send_raw(
                method="Overlay.hideHighlight",
                params=params,
                session_id=session_id,
            ),
        )

    async def getHighlightObjectForTest(
        self,
        params: "GetHighlightObjectForTestParameters",
        session_id: Optional[str] = None,
    ) -> "GetHighlightObjectForTestReturns":
        """For testing."""
        return cast(
            "GetHighlightObjectForTestReturns",
            await self._client.send_raw(
                method="Overlay.getHighlightObjectForTest",
                params=params,
                session_id=session_id,
            ),
        )
