# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Overlay Domain Types"""

from typing_extensions import Literal
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import RGBA


class HighlightConfig(TypedDict, total=False):
    """Configuration data for the highlighting of page elements."""

    showInfo: "bool"
    """Whether the node info tooltip should be shown (default: false)."""
    showRulers: "bool"
    """Whether the rulers should be shown (default: false)."""
    showExtensionLines: "bool"
    """Whether the extension lines from node to the rulers should be shown (default: false)."""
    displayAsMaterial: "bool"
    contentColor: "RGBA"
    """The content box highlight fill color (default: transparent)."""
    paddingColor: "RGBA"
    """The padding highlight fill color (default: transparent)."""
    borderColor: "RGBA"
    """The border highlight fill color (default: transparent)."""
    marginColor: "RGBA"
    """The margin highlight fill color (default: transparent)."""
    eventTargetColor: "RGBA"
    """The event target element highlight fill color (default: transparent)."""
    shapeColor: "RGBA"
    """The shape outside fill color (default: transparent)."""
    shapeMarginColor: "RGBA"
    """The shape margin fill color (default: transparent)."""
    selectorList: "str"
    """Selectors to highlight relevant nodes."""
    cssGridColor: "RGBA"
    """The grid layout color (default: transparent)."""


InspectMode = Literal["searchForNode", "searchForUAShadowDOM", "none"]
