# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Profiler Domain Commands"""

from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import Profile
    from .types import ScriptCoverage


class SetSamplingIntervalParameters(TypedDict):
    interval: "int"
    """New sampling interval in microseconds."""


class StopReturns(TypedDict):
    profile: "Profile"
    """Recorded profile."""


class StartPreciseCoverageParameters(TypedDict, total=False):
    callCount: "bool"
    """Collect accurate call counts beyond simple 'covered' or 'not covered'."""
    detailed: "bool"
    """Collect block-based coverage."""


class TakePreciseCoverageReturns(TypedDict):
    result: "List[ScriptCoverage]"
    """Coverage data for the current isolate."""


class GetBestEffortCoverageReturns(TypedDict):
    result: "List[ScriptCoverage]"
    """Coverage data for the current isolate."""
