# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Profiler Domain Events"""

from typing_extensions import NotRequired, TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..debugger.types import Location
    from .types import Profile

"""Sent when new profile recording is started using console.profile() call."""


class ConsoleProfileStartedEvent(TypedDict):
    id: "str"
    location: "Location"
    """Location of console.profile()."""
    title: "NotRequired[str]"
    """Profile title passed as an argument to console.profile()."""


class ConsoleProfileFinishedEvent(TypedDict):
    id: "str"
    location: "Location"
    """Location of console.profileEnd()."""
    profile: "Profile"
    title: "NotRequired[str]"
    """Profile title passed as an argument to console.profile()."""
